import { lazy, type ComponentType } from 'react'
import { Baby, Siren,
  Calculator,
  ClipboardList,
  FlaskConical,
  GraduationCap,
  Wind,
  type LucideIcon,
} from 'lucide-react'

import { chaveFerramenta } from '@/lib/useFavoritos'

/**
 * Carrega um export nomeado sob demanda (code-splitting por ferramenta).
 * O `ToolRouter` já envolve a renderização em <Suspense>.
 */
function sobDemanda(
  importar: () => Promise<Record<string, unknown>>,
  nome: string
): ComponentType {
  return lazy(async () => ({ default: (await importar())[nome] as ComponentType }))
}

export type ToolDef = {
  slug: string
  label: string
  description: string
  component: ComponentType
  tags?: string[]
  /** Para quem vale; sem declarar, vale a regra de src/content/publicoFerramentas.ts (padrão: adulto). */
  publico?: 'adulto' | 'pediatrico' | 'ambos' | 'sem_idade'
}

export type SectionDef = {
  slug: string
  label: string
  description: string
  icon: LucideIcon
  tools: ToolDef[]
}

const t = (
  slug: string,
  label: string,
  description: string,
  component: ComponentType,
  tags?: string[]
): ToolDef => ({ slug, label, description, component, tags })

export const SECOES: SectionDef[] = [
  {
    slug: 'calculadoras',
    label: 'Calculadoras',
    description: 'Cálculos de doses, diluições e decisões para o plantão.',
    icon: Calculator,
    tools: [
      t('iot', 'Intubação Orotraqueal (sequência rápida)', 'Indução, analgesia e bloqueio por peso (padrão HC).', sobDemanda(() => import('@/pages/plantonista/calculadoras/IsrAdulto'), 'IsrAdulto'), ['intubação', 'sequência rápida', 'sedação', 'anestesia', 'succinilcolina', 'propofol', 'IOT']),
      t('infusoes-adulto', 'Infusões contínuas — adulto', 'Porta única: vasoativas, sedação, bloqueio neuromuscular e atalhos da heparina, com barra de dose até o teto do manual HC.', sobDemanda(() => import('@/pages/plantonista/calculadoras/InfusoesAdulto'), 'InfusoesAdultoPorta'), ['infusão', 'bomba', 'mL/h', 'noradrenalina', 'sedação', 'fentanil', 'midazolam', 'rocurônio', 'vasoativa', 'DVA', 'diluição']),
      t('drogas-vasoativas', 'Drogas Vasoativas', 'Preparo padrão HC, mL/h pela dose e dose pela bomba.', sobDemanda(() => import('@/pages/plantonista/calculadoras/InfusoesAdulto'), 'DrogasVasoativas'), ['noradrenalina', 'vasopressor', 'infusão', 'diluição', 'dopamina', 'adrenalina', 'DVA']),
      t('sedacao-continua', 'Sedação Contínua', 'Propofol, midazolam, dexmedetomidina, quetamina e fentanil.', sobDemanda(() => import('@/pages/plantonista/calculadoras/InfusoesAdulto'), 'SedacaoContinua'), ['fentanil', 'midazolam', 'propofol', 'dexmedetomidina', 'cetamina', 'analgesia']),
      t('bloqueio-neuromuscular', 'Bloqueio Neuromuscular Contínuo', 'Rocurônio e cisatracúrio (padrão HC).', sobDemanda(() => import('@/pages/plantonista/calculadoras/InfusoesAdulto'), 'BloqueioNeuromuscular'), ['atracúrio', 'rocurônio', 'curarizante', 'paralisia']),
      t('heparinizacao-venosa', 'Heparina não fracionada EV', '80 UI/kg + 18 UI/kg/h e ajuste pelo TTPa (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/HeparinaNaoFracionadaAdulto'), 'HeparinaNaoFracionadaAdulto'), ['heparina', 'TTPa', 'anticoagulação', 'TVP', 'TEP']),
      t('hiponatremia', 'Hiponatremia', 'NaCl 3%: preparo, bolus e limites de correção (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/HiponatremiaManual'), 'HiponatremiaManual'), ['sódio', 'NaCl 3%', 'hiponatremia', 'eletrólitos']),
      t('hipernatremia', 'Hipernatremia', 'Água livre e Adrogué-Madias (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/HipernatremiaManual'), 'HipernatremiaManual'), ['sódio', 'água livre', 'hipernatremia', 'eletrólitos']),
      t('hidantalizacao', 'Estado de mal epiléptico', '1ª, 2ª e 3ª linha por peso (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/EstadoDeMalAdulto'), 'EstadoDeMalAdulto'), ['fenitoína', 'hidantal', 'crise convulsiva', 'epilepsia']),
      t('profilaxia-tev', 'Profilaxia de TEV', 'Doses de profilaxia pelo manual HC (sem escore de risco).', sobDemanda(() => import('@/pages/plantonista/manual/ProfilaxiaTEV'), 'ProfilaxiaTEV'), ['trombose', 'TEV', 'enoxaparina', 'Caprini', 'Pádua', 'TVP']),
      t('acesso-venoso', 'Escolha de Acesso Venoso', 'Recomendação de dispositivo por perfil e terapia.', sobDemanda(() => import('@/pages/plantonista/calculadoras/AcessoVenoso'), 'AcessoVenoso'), ['PICC', 'CVC', 'cateter', 'acesso venoso', 'periférico', 'central']),
      t('heparinizacao-ajuste', 'Heparina — ajuste pelo TTPa', 'Nomograma da Tabela 7 do manual HC.', sobDemanda(() => import('@/pages/plantonista/manual/HeparinaNaoFracionadaAdulto'), 'HeparinaNaoFracionadaAdulto'), ['heparina', 'TTPa', 'ajuste', 'anticoagulação']),
    ],
  },
  {
    slug: 'pediatria',
    label: 'Pediatria',
    description: 'PS Pediatria ICr-HCFMUSP: doses, infusões, RCP, via aérea, hidratação e escores (até antes dos 14 anos; sem neonato).',
    icon: Baby,
    tools: [
      t('bolus', 'Doses por peso', 'Apêndice do PS Pediatria ICr: emergência, RCP, sedação e antídotos.', sobDemanda(() => import('@/pages/plantonista/pediatria/BolusPediatrico'), 'BolusPediatrico'), ['pediatria', 'criança', 'dose', 'peso', 'emergência', 'antídoto']),
      t('infusoes', 'Infusões contínuas', 'Faixa de dose do livro e mL/h pela concentração do seu preparo.', sobDemanda(() => import('@/pages/plantonista/pediatria/InfusoesPediatricas'), 'InfusoesPediatricas'), ['pediatria', 'infusão', 'vasoativo', 'sedação', 'mL/h']),
      t('rcp-pediatrica', 'RCP pediátrica', 'Compressão/ventilação por faixa, cargas de desfibrilação e cardioversão por peso, drogas da PCR, bradicardia e TSV.', sobDemanda(() => import('@/pages/plantonista/pediatria/RcpPediatrica'), 'RcpPediatrica'), ['pediatria', 'RCP', 'PCR', 'parada', 'desfibrilação', 'cardioversão', 'joules', 'epinefrina']),
      t('via-aerea', 'Via aérea pediátrica', 'Tubo com e sem cuff, profundidade, equipamento por idade e doses da SRI.', sobDemanda(() => import('@/pages/plantonista/pediatria/ViaAereaPediatrica'), 'ViaAereaPediatrica'), ['pediatria', 'tubo', 'cuff', 'intubação', 'via aérea', 'SRI', 'laringoscópio', 'lâmina']),
      t('anafilaxia-pediatrica', 'Anafilaxia — criança', 'Epinefrina IM por peso ou dose fixa por idade, 2ª/3ª linha e refratária.', sobDemanda(() => import('@/pages/plantonista/pediatria/AnafilaxiaPediatrica'), 'AnafilaxiaPediatrica'), ['pediatria', 'anafilaxia', 'alergia', 'epinefrina', 'adrenalina', 'difenidramina', 'glucagon', 'fenoterol']),
      t('asma-pediatrica', 'Crise asmática — criança', 'Corticoide, ipratrópio, magnésio e salbutamol contínuo por peso; classificação da crise como referência.', sobDemanda(() => import('@/pages/plantonista/pediatria/AsmaPediatrica'), 'AsmaPediatrica'), ['pediatria', 'asma', 'crise asmática', 'broncoespasmo', 'salbutamol', 'ipratrópio', 'sulfato de magnésio', 'prednisolona']),
      t('pram', 'PRAM — gravidade da crise de asma (criança)', 'Cinco itens do exame, 0 a 12: leve, moderada ou grave (Ducharme 2008; aguarda o RT).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'Pram'), ['PRAM', 'asma', 'crise', 'gravidade', 'sibilância']),
      t('crise-epileptica-pediatrica', 'Crise epiléptica — criança', 'Benzodiazepínicos, ataque, fenobarbital e EME refratário por peso, com tempo de infusão.', sobDemanda(() => import('@/pages/plantonista/pediatria/CriseEpilepticaPediatrica'), 'CriseEpilepticaPediatrica'), ['pediatria', 'convulsão', 'crise epiléptica', 'estado de mal', 'diazepam', 'midazolam', 'fenitoína', 'fenobarbital']),
      t('sinais-vitais-pediatricos', 'Sinais vitais por idade', 'FC normal, valores anormais no choque, PA sistólica baixa e FR normal para a idade (só referência).', sobDemanda(() => import('@/pages/plantonista/pediatria/SinaisVitaisPediatricos'), 'SinaisVitaisPediatricos'), ['pediatria', 'sinais vitais', 'frequência cardíaca', 'frequência respiratória', 'pressão arterial', 'hipotensão']),
      t('choque-pediatrico', 'Choque séptico — criança', 'Expansão volêmica em mL/kg, vasoativas em µg/min e metas da primeira hora.', sobDemanda(() => import('@/pages/plantonista/pediatria/ChoquePediatrico'), 'ChoquePediatrico'), ['pediatria', 'choque', 'sepse', 'choque séptico', 'expansão volêmica', 'bolus', 'epinefrina', 'dopamina']),
      t('tce-grave-pediatrico', 'TCE grave — criança', 'NaCl 3% e manitol por peso; metas de PaCO₂, PIC, PPC e osmolaridade.', sobDemanda(() => import('@/pages/plantonista/pediatria/TcePediatrico'), 'TcePediatrico'), ['pediatria', 'TCE', 'trauma craniano', 'hipertensão intracraniana', 'salina hipertônica', 'NaCl 3%', 'manitol']),
      t('pecarn-menor-2-anos', 'TCE leve — menores de 2 anos (PECARN)', 'Figura 2 do cap. 16.', sobDemanda(() => import('@/pages/plantonista/pediatria/EscoresPediatricosP2'), 'PecarnMenor2'), ['pediatria', 'TCE', 'PECARN', 'tomografia', 'lactente']),
      t('pecarn-2-anos-ou-mais', 'TCE leve — 2 anos ou mais (PECARN)', 'Figura 3 do cap. 16.', sobDemanda(() => import('@/pages/plantonista/pediatria/EscoresPediatricosP2'), 'PecarnMaior2'), ['pediatria', 'TCE', 'PECARN', 'tomografia']),
      t('glasgow-pediatrico', 'Escala de Coma de Glasgow — criança', 'Com a escala modificada (James) para menores de 5 anos.', sobDemanda(() => import('@/pages/plantonista/pediatria/EscoresPediatricosP2'), 'GlasgowPediatrico'), ['pediatria', 'Glasgow', 'coma', 'consciência', 'TCE']),
      t('pops', 'POPS', 'Escore de Observação de Prioridade Pediátrica (Tabela 4 do cap. 82).', sobDemanda(() => import('@/pages/plantonista/pediatria/EscoresPediatricosP2'), 'PopsPediatrico'), ['pediatria', 'triagem', 'POPS', 'escore de alerta']),
      t('pews', 'PEWS', 'Escore de Alerta Precoce Pediátrico (Figura 2 do cap. 82).', sobDemanda(() => import('@/pages/plantonista/pediatria/EscoresPediatricosP2'), 'PewsPediatrico'), ['pediatria', 'triagem', 'PEWS', 'escore de alerta', 'deterioração']),
      t('phoenix', 'Escore de Phoenix — sepse (criança)', 'Sepse e choque séptico pediátricos pelos critérios de 2024 (JAMA).', sobDemanda(() => import('@/pages/plantonista/pediatria/PhoenixPed'), 'PhoenixPed'), ['Phoenix', 'sepse', 'choque séptico', 'disfunção orgânica']),
      t('fluidoterapia-manutencao-ped', 'Fluidoterapia de manutenção — criança', 'Holliday-Segar, regra prática (teto 100 mL/h), soluções-padrão e categorias da Figura 1.', sobDemanda(() => import('@/pages/plantonista/pediatria/FluidoterapiaManutencaoPed'), 'FluidoterapiaManutencaoPed'), ['soro de manutenção', 'Holliday-Segar', '4-2-1', 'hidratação venosa', 'soro isotônico', 'SIHAD']),
      t('desidratacao-diarreia-ped', 'Diarreia aguda — desidratação e planos', 'Escala clínica, grau pelo peso perdido, planos A/B/C por peso e idade.', sobDemanda(() => import('@/pages/plantonista/pediatria/DesidratacaoDiarreiaPed'), 'DesidratacaoDiarreiaPed'), ['diarreia', 'gastroenterite', 'desidratação', 'SRO', 'plano A', 'plano B', 'plano C', 'reidratação']),
      t('sodio-ped', 'Hipo e hipernatremia — criança', 'Na corrigido, osmolalidade efetiva, NaCl 3% por peso, Tabela 3 por litro, déficit de água livre.', sobDemanda(() => import('@/pages/plantonista/pediatria/DisturbiosSodioPed'), 'DisturbiosSodioPed'), ['sódio', 'hiponatremia', 'hipernatremia', 'NaCl 3%', 'salina hipertônica', 'água livre', 'Adrogué-Madias']),
      t('eletrolitos-ped', 'Potássio, cálcio, magnésio e fósforo — criança', 'Reposições e hipercalemia por peso, máximos, FEMg.', sobDemanda(() => import('@/pages/plantonista/pediatria/EletrolitosPed'), 'EletrolitosPed'), ['potássio', 'hipocalemia', 'hipercalemia', 'cálcio', 'gluconato', 'magnésio', 'sulfato de magnésio', 'fósforo']),
      t('cad-ehh-ped', 'Cetoacidose diabética e EHH — criança', 'Critérios, gravidade, Quadro 6, fluidos, K, insulina EV/SC, bicarbonato, edema cerebral.', sobDemanda(() => import('@/pages/plantonista/pediatria/CadEhhPed'), 'CadEhhPed'), ['cetoacidose', 'CAD', 'EHH', 'diabetes', 'insulina', 'potássio', 'edema cerebral', 'manitol']),
      t('hipoglicemia-ped', 'Hipoglicemia — glicose e glucagon por peso', 'Glicose VO/EV por idade (texto e Tabela 2), glucagon, VIG → mL/h.', sobDemanda(() => import('@/pages/plantonista/pediatria/HipoglicemiaPed'), 'HipoglicemiaPed'), ['hipoglicemia', 'glicose', 'soro glicosado', 'glucagon', 'VIG', 'TIG']),
      t('acidobase-ped', 'Distúrbios acidobásicos — criança', 'Leitura em 3 etapas, compensação (Tabela 3), ânion-gap, ΔAG/ΔHCO3, bicarbonato 1,4%, HCl.', sobDemanda(() => import('@/pages/plantonista/pediatria/AcidoBasePed'), 'AcidoBasePed'), ['gasometria', 'acidose', 'alcalose', 'ânion-gap', 'compensação', 'bicarbonato', 'delta-delta']),
      t('queimadura-ped', 'Queimadura — superfície queimada e Parkland (criança)', 'Lund e Browder por região e idade, Parkland (3 mL/kg/%SCQ) com manutenção e diurese-alvo.', sobDemanda(() => import('@/pages/plantonista/pediatria/QueimaduraPed'), 'QueimaduraPed'), ['queimadura', 'SCQ', 'Lund-Browder', 'Parkland', 'grande queimado', 'reposição volêmica']),
      t('intoxicacoes-ped', 'Intoxicações exógenas — criança', 'Descontaminação, eliminação e antídotos por peso, toxíndromes e tabela de antídotos.', sobDemanda(() => import('@/pages/plantonista/pediatria/IntoxicacoesPed'), 'IntoxicacoesPed'), ['intoxicação', 'envenenamento', 'antídoto', 'carvão ativado', 'toxíndrome', 'acetilcisteína', 'atropina', 'pralidoxima']),
      t('escorpiao-aranhas-ped', 'Escorpião e aranhas — soro por gravidade', 'Classe escolhida pelo médico → ampolas das Tabelas 1–4, volume do SAAr, prednisona e expansão.', sobDemanda(() => import('@/pages/plantonista/pediatria/PeconhentosPed'), 'PeconhentosPed'), ['escorpião', 'aranha', 'armadeira', 'aranha-marrom', 'viúva-negra', 'soro antiescorpiônico', 'SAAr', 'peçonhento']),
      t('sedacao-procedimento-ped', 'Sedação para procedimento — criança', 'Jejum, ASA, sugestões por procedimento, sedativos e reversores por peso.', sobDemanda(() => import('@/pages/plantonista/pediatria/SedacaoProcedimentoPed'), 'SedacaoProcedimentoPed'), ['sedação', 'analgesia', 'procedimento', 'jejum', 'cetamina', 'midazolam', 'fentanil', 'dexmedetomidina']),
      t('vias-aereas-superiores-ped', 'OMA, faringite, sinusite e crupe — criança', 'Antibióticos e corticoide por peso e gravidade do crupe (Tabela 6).', sobDemanda(() => import('@/pages/plantonista/pediatria/ViasAereasSuperioresPed'), 'ViasAereasSuperioresPed'), ['otite', 'OMA', 'faringite', 'amigdalite', 'sinusite', 'crupe', 'laringite', 'dexametasona']),
      t('bronquiolite-ped', 'Bronquiolite — internação, CNAF e palivizumabe', 'Indicações de internação, CNAF 1–2 L/kg/min, critérios de palivizumabe.', sobDemanda(() => import('@/pages/plantonista/pediatria/BronquiolitePed'), 'BronquiolitePed'), ['bronquiolite', 'VSR', 'sibilância', 'lactente', 'CNAF', 'alto fluxo', 'palivizumabe']),
      t('insuficiencia-cardiaca-ped', 'Insuficiência cardíaca — criança', 'Diuréticos, iECA, betabloqueadores, digoxina, levosimendana, ICT, Ross e ISHLT.', sobDemanda(() => import('@/pages/plantonista/pediatria/InsuficienciaCardiacaPed'), 'InsuficienciaCardiacaPed'), ['insuficiência cardíaca', 'furosemida', 'espironolactona', 'captopril', 'enalapril', 'carvedilol', 'digoxina', 'levosimendana']),
      t('crise-hipertensiva-ped', 'Crise hipertensiva — criança', 'Classificação da PA (Tabela 1) com p90/p95 informados, meta da PAM e drogas por peso.', sobDemanda(() => import('@/pages/plantonista/pediatria/CriseHipertensivaPed'), 'CriseHipertensivaPed'), ['hipertensão', 'crise hipertensiva', 'emergência hipertensiva', 'pressão arterial', 'percentil', 'hidralazina', 'isradipina', 'minoxidil']),
      t('meningite-ped', 'Meningite — criança', 'Acidente de punção, BMS, antibióticos neonatal/pós-neonatal, aciclovir, dexametasona e profilaxia.', sobDemanda(() => import('@/pages/plantonista/pediatria/MeningitePed'), 'MeningitePed'), ['meningite', 'liquor', 'LCR', 'BMS', 'ceftriaxona', 'cefotaxima', 'vancomicina', 'aciclovir']),
      t('infeccao-urinaria-ped', 'Infecção urinária — criança', 'Fatores da AAP, urocultura por método de coleta, antibióticos orais e parenterais por peso.', sobDemanda(() => import('@/pages/plantonista/pediatria/InfeccaoUrinariaPed'), 'InfeccaoUrinariaPed'), ['infecção urinária', 'ITU', 'pielonefrite', 'cistite', 'urocultura', 'UFC', 'cefalexina', 'ceftriaxona']),
      t('pneumonia-ped', 'Pneumonia adquirida na comunidade — criança', 'Antibiótico domiciliar/hospitalar por faixa e peso, situações especiais e líquido pleural.', sobDemanda(() => import('@/pages/plantonista/pediatria/PneumoniaPed'), 'PneumoniaPed'), ['pneumonia', 'PAC', 'amoxicilina', 'penicilina cristalina', 'ampicilina', 'derrame pleural', 'empiema', 'coqueluche']),
      t('hemocomponentes-ped', 'Hemocomponentes — volumes por peso', 'CH, PFC, plaquetas (fórmula da p. 727), fatores VIII/IX, crio, albumina e cálcio na maciça.', sobDemanda(() => import('@/pages/plantonista/pediatria/HemocomponentesPed'), 'HemocomponentesPed'), ['transfusão', 'concentrado de hemácias', 'plaquetas', 'plasma', 'crioprecipitado', 'fator VIII', 'hemofilia', 'albumina']),
      t('falciforme-ped', 'Doença falciforme — crise álgica e complicações agudas', 'Dor pela Figura 1, morfina e analgésicos por peso, febre, sequestro, AVC e STA.', sobDemanda(() => import('@/pages/plantonista/pediatria/FalciformePed'), 'FalciformePed'), ['falciforme', 'anemia falciforme', 'crise álgica', 'vaso-oclusiva', 'morfina', 'sequestro esplênico', 'síndrome torácica aguda']),
      t('kawasaki-ped', 'Doença de Kawasaki — critérios e doses', 'Critérios clássicos, forma incompleta (AHA), Z-score e doses por peso.', sobDemanda(() => import('@/pages/plantonista/pediatria/KawasakiPed'), 'KawasakiPed'), ['Kawasaki', 'vasculite', 'imunoglobulina', 'AAS', 'aneurisma coronariano', 'Z-score']),
      t('dengue-ped', 'Dengue — criança (grupos e hidratação)', 'Grupos A–D, hidratação por faixa de peso (Quadro 8), expansões C/D, albumina 5% e prova do laço.', sobDemanda(() => import('@/pages/plantonista/pediatria/DenguePed'), 'DenguePed'), ['dengue', 'arbovirose', 'hidratação', 'sinais de alarme', 'choque', 'prova do laço', 'grupo C', 'grupo D']),
      t('febre-sem-sinais-ped', 'Febre sem sinais localizatórios — criança', 'Faixa dos fluxogramas, leucograma/PCR de risco, coleta de urina e antibióticos por peso.', sobDemanda(() => import('@/pages/plantonista/pediatria/FebreSemSinaisPed'), 'FebreSemSinaisPed'), ['febre sem sinais localizatórios', 'FSSL', 'bacteriemia oculta', 'DBG', 'lactente febril', 'amoxicilina', 'cefuroxima', 'ceftriaxona']),
      t('insuficiencia-adrenal-ped', 'Crise adrenal — hidrocortisona por m²', 'Hidrocortisona em bolo/manutenção por SC informada, SF, fludrocortisona e alternativa do Apêndice.', sobDemanda(() => import('@/pages/plantonista/pediatria/InsuficienciaAdrenalPed'), 'InsuficienciaAdrenalPed'), ['insuficiência adrenal', 'crise adrenal', 'hidrocortisona', 'fludrocortisona', 'hiperplasia adrenal congênita', 'choque']),
      t('injuria-renal-ped', 'Injúria renal aguda — criança', 'KDIGO pediátrico, Schwartz, FeNa, sobrecarga hídrica, furosemida, contraste e Tabela 8.', sobDemanda(() => import('@/pages/plantonista/pediatria/InjuriaRenalPed'), 'InjuriaRenalPed'), ['injúria renal aguda', 'IRA', 'KDIGO', 'Schwartz', 'TFG', 'FeNa', 'sobrecarga hídrica', 'hipercalemia']),
      t('tfg-schwartz-ped', 'TFG estimada — Schwartz / CKiD (criança)', 'Estatura × k ÷ creatinina, com a constante do método (livro do ICr, Tabela 2).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'SchwartzPed'), ['Schwartz', 'CKiD', 'TFG', 'filtração glomerular', 'creatinina', 'função renal']),
      t('glomerulopatias-shu-ped', 'Síndromes nefrítica e nefrótica e SHU — criança', 'Pr/Cr, albumina 20% e diuréticos, GNPE, pulso de metilprednisolona e limiares da SHU.', sobDemanda(() => import('@/pages/plantonista/pediatria/GlomerulopatiasShuPed'), 'GlomerulopatiasShuPed'), ['síndrome nefrótica', 'síndrome nefrítica', 'GNPE', 'GNRP', 'albumina', 'furosemida', 'SHU', 'hemolítico-urêmica']),
      t('hemorragia-digestiva-hepatica-ped', 'Hemorragia digestiva e insuficiência hepática aguda — criança', 'Octreotida, somatostatina e omeprazol por peso; PALF, paracetamol, amônia e suporte da IHA.', sobDemanda(() => import('@/pages/plantonista/pediatria/DigestivoHepaticoPed'), 'DigestivoHepaticoPed'), ['hemorragia digestiva', 'HDA', 'varizes', 'octreotida', 'somatostatina', 'omeprazol', 'insuficiência hepática aguda', 'PALF']),
      t('coma-hic-ped', 'Coma e hipertensão intracraniana — criança', 'GCS-Pupilas, PPC e metas por idade, bainha do nervo óptico, glicose, midazolam e dexametasona.', sobDemanda(() => import('@/pages/plantonista/pediatria/ComaHicPed'), 'ComaHicPed'), ['coma', 'rebaixamento de consciência', 'hipertensão intracraniana', 'PIC', 'PPC', 'bainha do nervo óptico', 'dexametasona']),
      t('hemostasia-trombose-ped', 'Hemofilia, von Willebrand, PTI e anticoagulação — criança', 'Fator por tipo de sangramento, DDAVP, tranexâmico, PTI, heparina com nomograma, enoxaparina, varfarina.', sobDemanda(() => import('@/pages/plantonista/pediatria/HemostasiaTrombosePed'), 'HemostasiaTrombosePed'), ['hemofilia', 'fator VIII', 'fator IX', 'von Willebrand', 'PTI', 'heparina', 'enoxaparina', 'varfarina']),
      t('emergencias-oncologicas-ped', 'Emergências oncológicas — criança', 'Lise tumoral, hemocomponentes, hiperviscosidade, neutropenia febril (Tabela 11) e compressivas.', sobDemanda(() => import('@/pages/plantonista/pediatria/EmergenciasOncologicasPed'), 'EmergenciasOncologicasPed'), ['lise tumoral', 'rasburicase', 'alopurinol', 'hiperleucocitose', 'neutropenia febril', 'MASCC', 'cefepima', 'compressão medular']),
      t('choque-toxico-partes-moles-ped', 'Choque tóxico e infecções de pele e partes moles — criança', 'Critérios do CDC, penicilina + clindamicina + IGIV, antibióticos de pele (doses do Apêndice).', sobDemanda(() => import('@/pages/plantonista/pediatria/ChoqueToxicoPartesMolesPed'), 'ChoqueToxicoPartesMolesPed'), ['choque tóxico', 'SCT', 'estreptococo', 'estafilococo', 'celulite', 'erisipela', 'impetigo', 'fasceíte necrotizante']),
      t('febre-imunodeprimido-ped', 'Febre no imunodeprimido não oncológico — criança', 'Tabela 7 por peso com máximos do Apêndice, corticoide imunossupressor, profilaxias.', sobDemanda(() => import('@/pages/plantonista/pediatria/FebreImunodeprimidoPed'), 'FebreImunodeprimidoPed'), ['imunodeprimido', 'erro inato da imunidade', 'transplante', 'febre', 'cefepima', 'TMP-SMX', 'aciclovir', 'fluconazol']),
      t('artrite-osteomielite-ped', 'Artrite séptica e osteomielite — criança', 'Antibiótico por resistência local (doses mínimas), cobertura por idade, sinovial e duração.', sobDemanda(() => import('@/pages/plantonista/pediatria/ArtriteOsteomielitePed'), 'ArtriteOsteomielitePed'), ['artrite séptica', 'osteomielite', 'MRSA', 'MSSA', 'Kingella', 'oxacilina', 'clindamicina', 'vancomicina']),
    ],
  },
  {
    slug: 'emergencias',
    label: 'Emergências — manual HC',
    description: 'Doses, reposições e fórmulas do Manual de Medicina de Emergência do HCFMUSP (adulto).',
    icon: Siren,
    tools: [
      t('hipocalemia-reposicao-potassio', 'Hipocalemia — potássio', 'Classificação, KCl EV e VO, mEq/h e mL/h.', sobDemanda(() => import('@/pages/plantonista/manual/ReposicaoPotassio'), 'ReposicaoPotassio'), ['potássio', 'hipocalemia', 'KCl', 'reposição']),
      t('hipomagnesemia-reposicao-magnesio', 'Hipomagnesemia — magnésio', 'Esquemas de MgSO4 e preparo.', sobDemanda(() => import('@/pages/plantonista/manual/ReposicaoMagnesio'), 'ReposicaoMagnesio'), ['magnésio', 'hipomagnesemia', 'sulfato de magnésio']),
      t('hipocalcemia-reposicao-calcio', 'Hipocalcemia — cálcio', 'Cálcio corrigido, bolus e infusão.', sobDemanda(() => import('@/pages/plantonista/manual/DisturbiosCalcio'), 'ReposicaoCalcio'), ['cálcio', 'hipocalcemia', 'gluconato']),
      t('hipercalcemia', 'Hipercalcemia', 'Gravidade, FECa e tratamento agudo.', sobDemanda(() => import('@/pages/plantonista/manual/DisturbiosCalcio'), 'HipercalcemiaAdulto'), ['cálcio', 'hipercalcemia', 'calcitonina', 'bifosfonato']),
      t('hipofosfatemia-reposicao-fosforo', 'Hipofosfatemia — fósforo', 'Reposição IV e VO com limites.', sobDemanda(() => import('@/pages/plantonista/manual/ReposicaoFosforo'), 'ReposicaoFosforo'), ['fósforo', 'fosfato', 'hipofosfatemia']),
      t('gasometria-acidobase', 'Gasometria e distúrbios acidobásicos', 'Compensação, ânion-gap, delta-delta, gap osmolar.', sobDemanda(() => import('@/pages/plantonista/manual/AcidoBase'), 'GasometriaAcidoBase'), ['gasometria', 'acidose', 'alcalose', 'ânion-gap', 'Winter']),
      t('bicarbonato-de-sodio', 'Bicarbonato de sódio', 'Déficit e esquemas de preparo.', sobDemanda(() => import('@/pages/plantonista/manual/AcidoBase'), 'BicarbonatoAdulto'), ['bicarbonato', 'acidose metabólica', 'NaHCO3']),
      t('cad-ehh-criterios', 'CAD e EHH — critérios e fórmulas', 'Na corrigido, osmolaridade, ânion-gap e gravidade.', sobDemanda(() => import('@/pages/plantonista/manual/CadEhhAvaliacao'), 'CadEhhAvaliacao'), ['cetoacidose', 'CAD', 'EHH', 'osmolaridade']),
      t('cad-ehh-tratamento', 'CAD e EHH — tratamento', 'Hidratação, insulina EV, potássio e transição.', sobDemanda(() => import('@/pages/plantonista/manual/CadEhhTratamento'), 'CadEhhTratamento'), ['cetoacidose', 'CAD', 'EHH', 'insulina', 'potássio']),
      t('hipoglicemia-adulto', 'Hipoglicemia', 'Limiar e doses de glicose, glucagon e tiamina.', sobDemanda(() => import('@/pages/plantonista/manual/HipoglicemiaAdulto'), 'HipoglicemiaAdulto'), ['hipoglicemia', 'glicose', 'glucagon']),
      t('pcr-adulto', 'PCR — drogas e desfibrilação', 'Doses da Tabela 2 do HC e carga do choque.', sobDemanda(() => import('@/pages/plantonista/manual/PcrAdulto'), 'PcrAdulto'), ['PCR', 'parada', 'adrenalina', 'amiodarona', 'desfibrilação']),
      t('bradicardia-adulto', 'Bradicardia sintomática', 'Atropina, dopamina e adrenalina.', sobDemanda(() => import('@/pages/plantonista/manual/BradicardiaAdulto'), 'BradicardiaAdulto'), ['bradicardia', 'atropina', 'dopamina', 'marca-passo']),
      t('taquiarritmias-adulto', 'Taquiarritmias — drogas EV', 'Adenosina, amiodarona, lidocaína, verapamil, diltiazem, magnésio.', sobDemanda(() => import('@/pages/plantonista/manual/TaquiarritmiasAdulto'), 'TaquiarritmiasAdulto'), ['taquicardia', 'TSV', 'adenosina', 'amiodarona']),
      t('anafilaxia-adulto', 'Anafilaxia', 'Adrenalina IM/EV/infusão, volume e segunda linha.', sobDemanda(() => import('@/pages/plantonista/manual/AnafilaxiaAdulto'), 'AnafilaxiaAdulto'), ['anafilaxia', 'adrenalina', 'choque anafilático']),
      t('anticoagulacao-plena-adulto', 'Anticoagulação plena por peso', 'Enoxaparina com ajuste renal/idade, fondaparinux e outros.', sobDemanda(() => import('@/pages/plantonista/manual/AnticoagulacaoPlenaAdulto'), 'AnticoagulacaoPlenaAdulto'), ['enoxaparina', 'HBPM', 'fondaparinux', 'TVP', 'TEP', 'IAM', 'heparina', 'HNF']),
      t('fibrinoliticos-adulto', 'Fibrinolíticos', 'Estreptoquinase, alteplase e tenecteplase.', sobDemanda(() => import('@/pages/plantonista/manual/FibrinoliticosAdulto'), 'FibrinoliticosAdulto'), ['trombólise', 'alteplase', 'tenecteplase', 'IAM com supra', 'TEP']),
      t('intoxicacoes-antidotos-adulto', 'Intoxicações e antídotos — adulto', 'Carvão, NAC, antídotos, cardiotóxicos, digoxina, bicarbonato, álcoois, organofosforados e cianeto (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/IntoxicacoesAntidotosAdulto'), 'IntoxicacoesAntidotosAdulto'), ['intoxicação', 'envenenamento', 'antídoto', 'carvão ativado', 'paracetamol', 'acetaminofeno', 'N-acetilcisteína', 'NAC']),
      t('animais-peconhentos-adulto', 'Acidentes por animais peçonhentos — adulto', 'Ampolas de soro por gravidade, pré-medicação por peso e neostigmina (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/AnimaisPeconhentosAdulto'), 'AnimaisPeconhentosAdulto'), ['peçonhento', 'ofídico', 'cobra', 'serpente', 'jararaca', 'botrópico', 'cascavel', 'crotálico']),
      t('tetano-profilaxia-adulto', 'Tétano — profilaxia e tratamento (adulto)', 'Vacina e SAT/IGHAT por ferimento × histórico; doses do tratamento (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/ProfilaxiasPosExposicaoAdulto'), 'TetanoProfilaxiaAdulto'), ['tétano', 'antitetânica', 'dT', 'SAT', 'IGHAT', 'soro antitetânico', 'ferimento', 'vacina']),
      t('raiva-pos-exposicao-adulto', 'Raiva — profilaxia pós-exposição (adulto)', 'Fluxograma do Anexo 4: vacina, sorovacinação ou observação do animal.', sobDemanda(() => import('@/pages/plantonista/manual/ProfilaxiasPosExposicaoAdulto'), 'RaivaPosExposicaoAdulto'), ['raiva', 'antirrábica', 'mordedura', 'cão', 'gato', 'morcego', 'sorovacinação', 'vacina']),
      t('hepatite-b-pos-exposicao-adulto', 'Hepatite B — profilaxia pós-exposição ocupacional (adulto)', 'Fonte × situação vacinal → vacina, HBIG (mL por peso) e anti-HBs.', sobDemanda(() => import('@/pages/plantonista/manual/ProfilaxiasPosExposicaoAdulto'), 'HepatiteBPosExposicaoAdulto'), ['hepatite B', 'HBV', 'acidente biológico', 'perfurocortante', 'exposição ocupacional', 'HBIG', 'imunoglobulina', 'anti-HBs']),
      t('sedacao-procedimento-adulto', 'Sedação e analgesia para procedimentos — adulto', 'Etomidato, midazolam, propofol, quetamina EV/IM, fentanil e morfina por peso, reversores, níveis de sedação, ASA, jejum e alta.', sobDemanda(() => import('@/pages/plantonista/manual/SedacaoProcedimentoAdulto'), 'SedacaoProcedimentoAdulto'), ['sedação', 'SAP', 'sedação procedural', 'analgesia', 'etomidato', 'midazolam', 'propofol', 'quetamina']),
      t('dor-analgesia-adulto', 'Dor e analgesia — adulto', 'Escala numérica, escada analgésica, opioides da Tabela 3 com conta por peso e por dia, quetamina analgésica.', sobDemanda(() => import('@/pages/plantonista/manual/DorAnalgesiaAdulto'), 'DorAnalgesiaAdulto'), ['dor', 'analgesia', 'escada analgésica', 'OMS', 'opioide', 'codeína', 'tramadol', 'morfina']),
      t('sintomas-paliativos-adulto', 'Dor, dispneia e sedação em cuidados paliativos — adulto', 'Resgate de 1/6 da dose diária, morfina e midazolam na dispneia, quetamina e sedação paliativa com midazolam.', sobDemanda(() => import('@/pages/plantonista/manual/SintomasPaliativosAdulto'), 'SintomasPaliativosAdulto'), ['cuidados paliativos', 'paliativo', 'resgate', 'morfina', 'dispneia', 'sedação paliativa', 'midazolam', 'quetamina']),
      t('trombolise-avc-adulto', 'Trombólise no AVC isquêmico — adulto', 'Alteplase e tenecteplase por peso, critérios numéricos da Tabela 4, alvos de PA (com errata), nitroprussiato, sangramento e angioedema.', sobDemanda(() => import('@/pages/plantonista/manual/TromboliseAvcAdulto'), 'TromboliseAvcAdulto'), ['AVC', 'AVCi', 'stroke', 'trombólise', 'alteplase', 'rtPA', 'tenecteplase', 'TEV']),
      t('reversao-anticoagulacao-adulto', 'Reversão de anticoagulação e sangramento — adulto', 'Varfarina por INR × sangramento, CCP, plasma, vitamina K, crioprecipitado, protamina, DOAC e metas da HIP.', sobDemanda(() => import('@/pages/plantonista/manual/ReversaoAnticoagulacaoAdulto'), 'ReversaoAnticoagulacaoAdulto'), ['reversão', 'anticoagulação', 'varfarina', 'INR', 'vitamina K', 'CCP', 'complexo protrombínico', 'plasma', 'heparina', 'protamina']),
      t('escala-numerica-dor', 'Escala numérica de dor (0–10) — adulto', 'Nota de 0 a 10 com a faixa e o degrau da escada analgésica.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE2'), 'EscalaNumericaDor'), ['dor', 'escala numérica', 'EVA', 'escala visual analógica', 'intensidade']),
      t('painad', 'PAINAD — dor na demência avançada (adulto)', 'Cinco itens de 0 a 2; faixas 1–3/4–6/7–10 do livro.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE2'), 'Painad'), ['PAINAD', 'dor', 'demência', 'não verbal', 'paliativo']),
      t('bps-dor', 'BPS — Escala Comportamental de Dor (adulto)', 'Três itens de 1 a 4 para sedado ou em VM; o livro não traz corte.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE2'), 'Bps'), ['BPS', 'Behavioural Pain Scale', 'dor', 'sedação', 'ventilação mecânica', 'UTI']),
      t('rankin-modificada', 'Escala de Rankin modificada (manual do HC)', 'Grau 0 a 6 com os cortes do capítulo (trombólise, trombectomia, hemicraniectomia).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE2'), 'RankinModificada'), ['Rankin', 'ERm', 'mRS', 'AVC', 'funcionalidade']),
      t('escore-ich', 'Escore ICH — hemorragia intraparenquimatosa (adulto)', 'Glasgow, volume, extensão ventricular, infratentorial e idade, com a mortalidade em 30 dias da Tabela 2.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE2'), 'EscoreIch'), ['ICH', 'escore ICH', 'hemorragia intraparenquimatosa', 'HIP', 'AVC hemorrágico', 'prognóstico']),
      t('transfusao-hemocomponentes-adulto', 'Transfusão de hemocomponentes — adulto', 'Gatilhos, incremento esperado, volume e velocidade de CH, plaquetas, PFC, crioprecipitado e CCP.', sobDemanda(() => import('@/pages/plantonista/manual/TransfusaoAdulto'), 'TransfusaoAdulto'), ['transfusão', 'hemotransfusão', 'hemocomponente', 'concentrado de hemácias', 'CH', 'plaquetas', 'aférese', 'plasma']),
      t('abc-score-transfusao-macica', 'ABC score — previsão de transfusão maciça (adulto)', 'Quatro critérios de 1 ponto com os dois cortes do manual (≥ 2 e > 2).', sobDemanda(() => import('@/pages/plantonista/manual/AbcTransfusaoMacica'), 'AbcTransfusaoMacica'), ['ABC score', 'transfusão maciça', 'protocolo de transfusão maciça', 'PTM', 'trauma', 'FAST', 'choque hemorrágico']),
      t('ressuscitacao-volemica-adulto', 'Ressuscitação volêmica no choque e na sepse — adulto', '30 mL/kg e alíquotas, metas de PAM/diurese/lactato, gatilho de vasopressina, corticoide, soluções.', sobDemanda(() => import('@/pages/plantonista/manual/RessuscitacaoVolemicaAdulto'), 'RessuscitacaoVolemicaAdulto'), ['choque', 'choque séptico', 'sepse', 'ressuscitação volêmica', 'expansão volêmica', 'cristaloide', 'Ringer lactato', 'soro fisiológico']),
      t('asma-exacerbacao-adulto', 'Exacerbação de asma — adulto', 'Parâmetros na Tabela 1, β2, ipratrópio, corticoide e sulfato de magnésio com preparo.', sobDemanda(() => import('@/pages/plantonista/manual/AsmaExacerbacaoAdulto'), 'AsmaExacerbacaoAdulto'), ['asma', 'crise asmática', 'broncoespasmo', 'exacerbação', 'fenoterol', 'salbutamol', 'ipratrópio', 'sulfato de magnésio']),
      t('dpoc-exacerbacao-adulto', 'Exacerbação de DPOC — adulto', 'Sintomas cardinais, cortes gasométricos, broncodilatador, corticoide, VNI e VM inicial.', sobDemanda(() => import('@/pages/plantonista/manual/DpocExacerbacaoAdulto'), 'DpocExacerbacaoAdulto'), ['DPOC', 'exacerbação', 'enfisema', 'bronquite crônica', 'VNI', 'BiPAP', 'IPAP', 'EPAP']),
      t('vm-ajuste-inicial-adulto', 'Ventilação mecânica — ajuste inicial (adulto)', 'Indicações (PO2 < 60, PCO2 > 55), Tabela 2 por modo, Vt 6–8 mL/kg pelo peso informado, I:E, pós-intubação, DOPE e assincronias.', sobDemanda(() => import('@/pages/plantonista/manual/VmAjusteInicialAdulto'), 'VmAjusteInicialAdulto'), ['ventilação mecânica', 'VM', 'ventilador', 'intubação', 'IOT', 'PCV', 'VCV', 'PSV']),
      t('vm-obstruido-grave-adulto', 'Ventilação mecânica no obstruído grave (adulto)', 'Tabela 4: Vt 6 mL/kg, PEEP a 85% da auto-PEEP, FR 8–12, I:E ≥ 1:3 e ≤ 1:5, limites de platô e pico, conferência do ventilador.', sobDemanda(() => import('@/pages/plantonista/manual/VmObstruidoGraveAdulto'), 'VmObstruidoGraveAdulto'), ['ventilação mecânica', 'obstruído', 'asma', 'DPOC', 'broncoespasmo', 'auto-PEEP', 'hiperinsuflação dinâmica', 'relação I:E']),
      t('mecanica-ventilatoria-adulto', 'Mecânica ventilatória (adulto)', 'Resistência, complacência estática, constante de tempo e driving pressure com as faixas do livro; exemplo da Figura 2.', sobDemanda(() => import('@/pages/plantonista/manual/MecanicaVentilatoriaAdulto'), 'MecanicaVentilatoriaAdulto'), ['mecânica ventilatória', 'resistência', 'complacência', 'complacência estática', 'constante de tempo', 'driving pressure', 'pressão de platô', 'pausa inspiratória']),
      t('sdra-ventilacao-adulto', 'SDRA — ventilação protetora (adulto)', 'Berlim pela P/F, Vt por gravidade, tabelas PEEP × FiO2 (ARDSnet, ALVEOLI, LOVS), driving pressure, marcos de prona e bloqueio.', sobDemanda(() => import('@/pages/plantonista/manual/SdraVentilacaoAdulto'), 'SdraVentilacaoAdulto'), ['SDRA', 'SARA', 'ARDS', 'Berlim', 'P/F', 'relação PaO2/FiO2', 'ventilação protetora', 'PEEP']),
      t('desmame-vm-adulto', 'Desmame da ventilação mecânica (adulto)', 'Parâmetros para o TRE (PO2 ≥ 60 com FiO2 ≤ 0,4, P/F ≥ 150, PEEP ≤ 5 a 8, FC < 140) e critérios de falência durante o teste.', sobDemanda(() => import('@/pages/plantonista/manual/DesmameVmAdulto'), 'DesmameVmAdulto'), ['desmame', 'extubação', 'teste de respiração espontânea', 'TRE', 'PSV', 'ventilação mecânica', 'weaning']),
      t('oxigenacao-irpa-adulto', 'Oxigenação e insuficiência respiratória — adulto', 'Gradiente A-a e esperado por idade, P/F, tipo de IRpA, hipercapnia aguda × crônica, FiO2 dos dispositivos, alvos de SatO2, cortes de VNI e IOT.', sobDemanda(() => import('@/pages/plantonista/manual/OxigenacaoIrpaAdulto'), 'OxigenacaoIrpaAdulto'), ['insuficiência respiratória', 'IRpA', 'hipoxemia', 'hipercapnia', 'gradiente alvéolo-arterial', 'gradiente A-a', 'P/F', 'oxigenoterapia']),
      t('dispneia-abordagem-adulto', 'Dispneia — abordagem inicial (adulto)', 'Cortes de gravidade, ABCDE, oxigênio, índice cardiotorácico, BNP e história, com o que o livro diz de cada um.', sobDemanda(() => import('@/pages/plantonista/manual/DispneiaAdulto'), 'DispneiaAdulto'), ['dispneia', 'falta de ar', 'desconforto respiratório', 'taquipneia', 'hipoxemia', 'índice cardiotorácico', 'BNP', 'insuficiência cardíaca']),
      t('fibrilacao-atrial-adulto', 'Fibrilação atrial — adulto', 'Esmolol, verapamil, diltiazem, digoxina e amiodarona por peso com mL/h da Tabela 3; propafenona; janela de 48 h e anticoagulação.', sobDemanda(() => import('@/pages/plantonista/manual/FibrilacaoAtrialAdulto'), 'FibrilacaoAtrialAdulto'), ['fibrilação atrial', 'FA', 'controle de frequência', 'controle de ritmo', 'esmolol', 'verapamil', 'diltiazem', 'digoxina']),
      t('emergencia-hipertensiva-adulto', 'Emergência hipertensiva — adulto', 'Alvo de PA/FC com tempo por condição (Tabela 4), regra geral 20–25% e 160/100, esmolol, nitroprussiato, nitroglicerina e hidralazina com mL/h.', sobDemanda(() => import('@/pages/plantonista/manual/EmergenciaHipertensivaAdulto'), 'EmergenciaHipertensivaAdulto'), ['emergência hipertensiva', 'crise hipertensiva', 'urgência hipertensiva', 'DOMH', 'pressão arterial', 'esmolol', 'nitroprussiato', 'nitroglicerina']),
      t('sindrome-aortica-adulto', 'Síndrome aórtica aguda — adulto', 'Alvo PAS < 120 e FC < 60 na dissecção, cortes de diâmetro e complicações anuais por tamanho da aorta.', sobDemanda(() => import('@/pages/plantonista/manual/SindromeAorticaAdulto'), 'SindromeAorticaAdulto'), ['síndrome aórtica', 'dissecção de aorta', 'hematoma intramural', 'úlcera penetrante', 'aneurisma de aorta', 'Stanford', 'diâmetro aórtico']),
      t('add-rs-disseccao-aorta', 'ADD-RS — risco de dissecção de aorta (adulto)', 'Um ponto por coluna (0–3) e leitura do D-dímero < / ≥ 500 ng/mL FEU para 0–1 ponto.', sobDemanda(() => import('@/pages/plantonista/manual/AddRsDisseccaoAorta'), 'AddRsDisseccaoAorta'), ['ADD-RS', 'dissecção de aorta', 'D-dímero', 'síndrome aórtica', 'angiotomografia', 'escore']),
      t('insuficiencia-cardiaca-aguda-adulto', 'Insuficiência cardíaca aguda — adulto', 'Perfil A/B/C/L, coluna de PAS da Figura 1, furosemida por peso, resposta ao diurético, inotrópicos com mL/h, peptídeos, prognóstico e critérios de UTI.', sobDemanda(() => import('@/pages/plantonista/manual/InsuficienciaCardiacaAgudaAdulto'), 'InsuficienciaCardiacaAgudaAdulto'), ['insuficiência cardíaca', 'ICA', 'IC descompensada', 'edema agudo de pulmão', 'perfil hemodinâmico', 'furosemida', 'levosimendana', 'dobutamina']),
      t('pos-pcr-adulto', 'Cuidados pós-PCR — adulto', 'Metas numéricas, SF 0,9% a 4 °C por peso, tempos de resfriamento e reaquecimento, milrinona, amiodarona na tempestade elétrica e janelas do neuroprognóstico.', sobDemanda(() => import('@/pages/plantonista/manual/PosPcrAdulto'), 'PosPcrAdulto'), ['pós-PCR', 'pós-parada', 'RCE', 'controle de temperatura', 'hipotermia terapêutica', 'reaquecimento', 'soro gelado', 'tempestade elétrica']),
      t('trauma-inicial-adulto', 'Politraumatizado — tempos e volumes (adulto)', 'Janela e velocidade do ácido tranexâmico, débito do dreno no hemotórax, torniquete, cristaloide antes da transfusão e critérios de coluna.', sobDemanda(() => import('@/pages/plantonista/manual/TraumaInicialAdulto'), 'TraumaInicialAdulto'), ['trauma', 'politrauma', 'ATLS', 'ácido tranexâmico', 'CRASH-2', 'hemotórax', 'toracotomia', 'torniquete']),
      t('nexus-coluna-cervical', 'NEXUS — retirada do colar cervical (adulto)', 'Cinco critérios; não se aplica acima de 60 anos nem em criança.', sobDemanda(() => import('@/pages/plantonista/manual/NexusColunaCervical'), 'NexusColunaCervical'), ['NEXUS', 'coluna cervical', 'colar cervical', 'trauma', 'imagem cervical']),
      t('regra-canadense-coluna-cervical', 'Regra canadense da coluna cervical (adulto)', 'Alto risco, baixo risco e rotação a 45°, como a Tabela 1 do livro imprime, com a errata.', sobDemanda(() => import('@/pages/plantonista/manual/RegraCanadenseColuna'), 'RegraCanadenseColuna'), ['regra canadense', 'Canadian C-Spine', 'coluna cervical', 'colar cervical', 'trauma', 'tomografia']),
      t('mgap-trauma', 'MGAP — gravidade do trauma no pré-hospitalar (adulto)', 'Mecanismo, Glasgow, idade e PAS (3–29), com a errata dos rótulos de gravidade.', sobDemanda(() => import('@/pages/plantonista/manual/MgapTrauma'), 'MgapTrauma'), ['MGAP', 'trauma', 'pré-hospitalar', 'APH', 'SAMU', 'gravidade', 'regulação']),
      t('triage-rts-trauma', 'Triage-RTS — escore de trauma revisado de triagem (adulto)', 'Glasgow, PAS e frequência ventilatória (0–12); < 11 indica centro de trauma.', sobDemanda(() => import('@/pages/plantonista/manual/TriageRtsTrauma'), 'TriageRtsTrauma'), ['RTS', 'Triage-RTS', 'trauma', 'pré-hospitalar', 'APH', 'triagem', 'centro de trauma']),
      t('hemorragia-digestiva-adulto', 'Hemorragia digestiva alta e baixa — adulto', 'Metas, omeprazol em dose alta, vasoativos nas varizes, antibiótico no cirrótico, Forrest, índice de choque.', sobDemanda(() => import('@/pages/plantonista/manual/HemorragiaDigestivaAdulto'), 'HemorragiaDigestivaAdulto'), ['HDA', 'HDB', 'hemorragia digestiva', 'hematêmese', 'melena', 'hematoquezia', 'varizes esofágicas', 'omeprazol']),
      t('oakland-hdb', 'Escore de Oakland — hemorragia digestiva baixa', 'Idade, sexo, HDB prévia, FC, PAS e Hb, com o corte do sangramento menor e a errata do 8.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE6'), 'OaklandHdb'), ['Oakland', 'HDB', 'hemorragia digestiva baixa', 'hematoquezia', 'alta ambulatorial', 'colonoscopia']),
      t('ascite-pbe-hepatorrenal-adulto', 'Ascite, PBE e síndrome hepatorrenal — adulto', 'GASA, albumina pós-paracentese, na PBE e na SHR, terlipressina escalonada e estádio ICA-AKI.', sobDemanda(() => import('@/pages/plantonista/manual/AsciteHepatorrenalAdulto'), 'AsciteHepatorrenalAdulto'), ['ascite', 'cirrose', 'GASA', 'paracentese', 'albumina', 'PBE', 'peritonite bacteriana espontânea', 'ceftriaxona']),
      t('encefalopatia-hepatites-graves-adulto', 'Encefalopatia hepática e hepatites graves — adulto', 'West Haven, lactulose, meta nutricional, King\'s College, N-acetilcisteína e plasma.', sobDemanda(() => import('@/pages/plantonista/manual/InsuficienciaHepaticaAdulto'), 'InsuficienciaHepaticaAdulto'), ['encefalopatia hepática', 'West Haven', 'lactulose', 'neomicina', 'rifaximina', 'hepatite fulminante', 'insuficiência hepática aguda', 'King’s College']),
      t('maddrey', 'Função discriminante de Maddrey — hepatite alcoólica', '4,6 × (TP − controle) + bilirrubina, corte de 32.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE6'), 'MaddreyHepatiteAlcoolica'), ['Maddrey', 'função discriminante', 'hepatite alcoólica', 'prednisona', 'TP']),
      t('lesao-renal-aguda-adulto', 'Lesão renal aguda — adulto', 'Estágio KDIGO por creatinina e diurese, FENa, FEUr, índices urinários, teste de furosemida e indicações de diálise.', sobDemanda(() => import('@/pages/plantonista/manual/LesaoRenalAgudaAdulto'), 'LesaoRenalAgudaAdulto'), ['LRA', 'lesão renal aguda', 'insuficiência renal aguda', 'KDIGO', 'creatinina', 'diurese', 'oligúria', 'FENa']),
      t('rabdomiolise-adulto', 'Rabdomiólise — adulto', 'CPK × LSN, hidratação, solução de bicarbonato e manitol da Tabela 3.', sobDemanda(() => import('@/pages/plantonista/manual/RabdomioliseAdulto'), 'RabdomioliseAdulto'), ['rabdomiólise', 'CPK', 'CK', 'mioglobinúria', 'esmagamento', 'hidratação', 'bicarbonato', 'manitol']),
      t('mcmahon-rabdomiolise', 'Escore de McMahon — rabdomiólise', 'Risco de óbito ou diálise pela Tabela 2 (< 5 e > 10 pontos).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE6'), 'McMahonRabdomiolise'), ['McMahon', 'rabdomiólise', 'diálise', 'CPK', 'prognóstico']),
      t('crise-tireotoxica-adulto', 'Crise tireotóxica — adulto', 'Propiltiouracil, metimazol, iodo, lítio, betabloqueadores e corticoide com totais diários.', sobDemanda(() => import('@/pages/plantonista/manual/CriseTireotoxicaAdulto'), 'CriseTireotoxicaAdulto'), ['crise tireotóxica', 'tempestade tireoidiana', 'tireotoxicose', 'hipertireoidismo', 'propiltiouracil', 'PTU', 'metimazol', 'iodo']),
      t('burch-wartofsky', 'Burch-Wartofsky — crise tireotóxica', 'Soma da Tabela 4 com as faixas improvável, iminente e crise.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE6'), 'BurchWartofsky'), ['Burch-Wartofsky', 'crise tireotóxica', 'tempestade tireoidiana', 'tireotoxicose']),
      t('estado-mixedematoso-adulto', 'Estado mixedematoso — adulto', 'T4, T3 e hidrocortisona e suporte da Tabela 5.', sobDemanda(() => import('@/pages/plantonista/manual/EstadoMixedematosoAdulto'), 'EstadoMixedematosoAdulto'), ['mixedema', 'coma mixedematoso', 'estado mixedematoso', 'hipotireoidismo', 'levotiroxina', 'T4', 'T3', 'hidrocortisona']),
      t('escore-mixedema', 'Escore diagnóstico do estado mixedematoso', 'Soma da Tabela 3 com os cortes 25 e 60.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE6'), 'EscoreMixedema'), ['mixedema', 'coma mixedematoso', 'hipotireoidismo', 'escore diagnóstico']),
      t('insuficiencia-adrenal-adulto', 'Insuficiência adrenal e crise adrenal — adulto', 'Cortes do cortisol, hidrocortisona, fludrocortisona e volume; corticoide no choque séptico refratário.', sobDemanda(() => import('@/pages/plantonista/manual/InsuficienciaAdrenalAdulto'), 'InsuficienciaAdrenalAdulto'), ['insuficiência adrenal', 'crise adrenal', 'Addison', 'cortisol', 'ACTH', 'hidrocortisona', 'fludrocortisona', 'choque séptico']),
      t('agitacao-delirium-adulto', 'Paciente agitado e delirium — adulto', 'Contenção química por nível (Tabela 4), quetamina por peso, contenção mecânica, shock index, antipsicóticos da Tabela 7 no delirium e síndrome neuroléptica maligna (dantroleno por peso).', sobDemanda(() => import('@/pages/plantonista/manual/AgitacaoDeliriumAdulto'), 'AgitacaoDeliriumAdulto'), ['agitação', 'paciente agitado', 'contenção química', 'contenção mecânica', 'haloperidol', 'midazolam', 'lorazepam', 'prometazina']),
      t('bars-agitacao', 'BARS — escala de atividade comportamental (adulto)', 'Níveis 1 a 7 com a triagem pré-hospitalar da Tabela 1.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'BarsAgitacao'), ['BARS', 'agitação', 'Behavioral Activity Rating Scale', 'pré-hospitalar', 'sedação']),
      t('hsa-adulto', 'Hemorragia subaracnóidea — nimodipino e metas (adulto)', 'Nimodipino 60 mg 4/4 h por 21 dias com a conta de doses e as metas numéricas do capítulo.', sobDemanda(() => import('@/pages/plantonista/manual/HsaAdulto'), 'HsaAdulto'), ['HSA', 'hemorragia subaracnóidea', 'aneurisma', 'nimodipino', 'vasoespasmo', 'PIC', 'PPC', 'Doppler transcraniano']),
      t('ottawa-hsa', 'Regra de Ottawa para HSA (adulto)', 'Seis itens; qualquer positivo indica investigação de HSA.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'OttawaHsa'), ['Ottawa', 'HSA', 'cefaleia súbita', 'thunderclap', 'hemorragia subaracnóidea']),
      t('hunt-hess', 'Classificação de Hunt-Hess — HSA (adulto)', 'Grau clínico I a V na admissão (Tabela 3).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'HuntHess'), ['Hunt-Hess', 'HSA', 'hemorragia subaracnóidea', 'grau clínico']),
      t('wfns-hsa', 'Escala WFNS ("CFIN" no livro) — HSA (adulto)', 'Grau 1 a 5 por Glasgow e déficit motor (Tabela 4).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'WfnsHsa'), ['WFNS', 'CFIN', 'HSA', 'Glasgow', 'hemorragia subaracnóidea']),
      t('fisher-hsa', 'Classificação de Fisher — HSA na TC (adulto)', 'Padrão do sangramento na TC, 1 a 4 (Tabela 5), para risco de vasoespasmo.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'FisherHsa'), ['Fisher', 'HSA', 'tomografia', 'vasoespasmo']),
      t('hints-plus', 'HINTS e HINTS plus — síndrome vestibular aguda (adulto)', 'Impulso cefálico, nistagmo, skew e audição: padrão periférico × central.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'HintsPlus'), ['HINTS', 'HINTS plus', 'vertigem', 'tontura', 'síndrome vestibular aguda', 'AVC de fossa posterior', 'nistagmo', 'skew']),
      t('guillain-barre-adulto', 'Síndrome de Guillain-Barré — imunoterapia e LCR (adulto)', 'Imunoglobulina e plasmaférese por peso, leitura do liquor, red flags e recomendações da AAN.', sobDemanda(() => import('@/pages/plantonista/manual/GuillainBarreAdulto'), 'GuillainBarreAdulto'), ['Guillain-Barré', 'SGB', 'paralisia flácida', 'imunoglobulina', 'IgIV', 'plasmaférese', 'liquor', 'dissociação proteinocitológica']),
      t('criterios-vm-sgb', 'Critérios de ventilação mecânica na SGB (adulto)', 'pCO2, pO2, CVF em mL/kg e PImáx (maiores) e três menores; 1 maior ou 2 menores.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'CriteriosVmSgb'), ['Guillain-Barré', 'SGB', 'intubação', 'ventilação mecânica', 'CVF', 'PImáx', 'capacidade vital']),
      t('gbs-incapacidade', 'Escore GBS de incapacidade (adulto)', 'Grau funcional 0 a 6 (Tabela 5), com o corte ≥ 3 do capítulo.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'IncapacidadeGbs'), ['Guillain-Barré', 'GBS disability score', 'incapacidade', 'SGB']),
      t('egos', 'Erasmus GBS Outcome Score — EGOS (adulto)', 'Idade, diarreia prévia e incapacidade em 2 semanas: 1 a 7.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'Egos'), ['EGOS', 'Erasmus', 'Guillain-Barré', 'prognóstico', 'marcha']),
      t('perc', 'PERC — critérios para descartar TEP (adulto)', 'Oito critérios; todos negativos descartam com probabilidade pré-teste improvável (com a errata do Wells simplificado).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'Perc'), ['PERC', 'TEP', 'embolia pulmonar', 'rule-out', 'D-dímero']),
      t('hestia', 'Critérios HESTIA — tratamento ambulatorial do TEP (adulto)', 'Onze critérios de exclusão; combinados com PESI I ou II.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'Hestia'), ['HESTIA', 'TEP', 'embolia pulmonar', 'tratamento ambulatorial', 'alta precoce']),
      t('smart-cop', 'SMART-COP — necessidade de suporte intensivo na PAC (adulto)', 'Oito variáveis; ≥ 3 pontos no protocolo do HC (cap. 90 usa > 3).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'SmartCop'), ['SMART-COP', 'pneumonia', 'PAC', 'UTI', 'vasopressor', 'ventilação']),
      t('ats-idsa-pac', 'Critérios ATS/IDSA de PAC grave (adulto)', '2 maiores e 9 menores; mostra a regra do livro (2 menores) e a da diretriz (3 menores).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'AtsIdsaPac'), ['ATS', 'IDSA', 'pneumonia grave', 'PAC', 'UTI']),
      t('pac-antibiotico-adulto', 'PAC — antibiótico por grupo de risco (adulto)', 'Esquemas da Tabela 10 por grupo, destino por PORT, fatores de Pseudomonas, metilprednisolona por peso, procalcitonina e alta.', sobDemanda(() => import('@/pages/plantonista/manual/PacAntibioticoAdulto'), 'PacAntibioticoAdulto'), ['pneumonia', 'PAC', 'antibiótico', 'amoxicilina', 'azitromicina', 'claritromicina', 'levofloxacino', 'ceftriaxona']),
      t('mascc', 'MASCC — risco na neutropenia febril (adulto)', 'Soma 0 a 26; < 21 é critério de alto risco (com a errata de sintomas graves).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'Mascc'), ['MASCC', 'neutropenia febril', 'oncologia', 'quimioterapia', 'risco']),
      t('neutropenia-febril-adulto', 'Neutropenia febril — definições e doses (adulto)', 'Definições, β-lactâmicos antipseudomonas, indicações de Gram-positivo, antifúngicos por peso e duração.', sobDemanda(() => import('@/pages/plantonista/manual/NeutropeniaFebrilAdulto'), 'NeutropeniaFebrilAdulto'), ['neutropenia febril', 'febre', 'quimioterapia', 'cefepime', 'piperacilina-tazobactam', 'meropenem', 'voriconazol', 'anfotericina']),
      t('cairo-bishop', 'Critérios de Cairo-Bishop — síndrome de lise tumoral (adulto)', 'SLT laboratorial (2 critérios) e clínica (+1 critério clínico).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'CairoBishop'), ['Cairo-Bishop', 'lise tumoral', 'SLT', 'ácido úrico', 'hipercalemia', 'hiperfosfatemia', 'oncologia']),
      t('lise-tumoral-adulto', 'Síndrome de lise tumoral — adulto', 'Risco da Tabela 2, hidratação por m², diurese-alvo, alopurinol com ajuste renal, rasburicase por peso e produto Ca × P.', sobDemanda(() => import('@/pages/plantonista/manual/LiseTumoralAdulto'), 'LiseTumoralAdulto'), ['lise tumoral', 'SLT', 'alopurinol', 'rasburicase', 'febuxostate', 'hidratação', 'hemodiálise', 'oncologia']),
      t('falciforme-adulto', 'Anemia falciforme — crise álgica e STA (adulto)', '50 mL/kg/24 h, analgesia da Tabela 5 com morfina e quetamina por peso, antibiótico da STA, metas e alta.', sobDemanda(() => import('@/pages/plantonista/manual/FalciformeAdulto'), 'FalciformeAdulto'), ['falciforme', 'anemia falciforme', 'crise álgica', 'vaso-oclusiva', 'morfina', 'quetamina', 'síndrome torácica aguda', 'hidratação']),
      t('sindrome-toracica-aguda-adulto', 'Síndrome torácica aguda — critérios diagnósticos (adulto)', 'Infiltrado novo + ≥ 1 dos 7 critérios da Tabela 3.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'SindromeToracicaAguda'), ['síndrome torácica aguda', 'STA', 'falciforme']),
      t('szpilman-afogamento', 'Afogamento — graus de Szpilman e prognóstico (adulto)', 'Grau 0 a VI com a sobrevida da Tabela 1 e os indicadores de pior prognóstico.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'Szpilman'), ['afogamento', 'Szpilman', 'submersão', 'edema pulmonar', 'prognóstico']),
      t('hipotermia-adulto', 'Hipotermia acidental — estágio, RCP e reaquecimento (adulto)', 'Estágio HT I-IV, regras de RCP/adrenalina/choque pela temperatura, método e taxa de reaquecimento.', sobDemanda(() => import('@/pages/plantonista/manual/HipotermiaAdulto'), 'HipotermiaAdulto'), ['hipotermia', 'hipotermia acidental', 'reaquecimento', 'RCP', 'temperatura central', 'ECMO', 'Osborn']),
      t('regiscar', 'RegiSCAR — escore para DRESS (adulto)', 'Soma −4 a 9; < 2 exclui, 2-3 possível, 4-5 provável, > 5 definitivo.', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'RegiScar'), ['RegiSCAR', 'DRESS', 'farmacodermia', 'eosinofilia', 'reação a droga']),
      t('scorten-uti', 'SSJ/NET — itens do SCORTEN para vaga de UTI (adulto)', 'Sete itens; dois ou mais é o critério do livro para UTI (sem mortalidade).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE7'), 'ScortenUti'), ['SCORTEN', 'Stevens-Johnson', 'necrólise epidérmica tóxica', 'NET', 'SSJ', 'UTI']),
      t('dermatoses-graves-adulto', 'Dermatoses graves — doses (adulto)', 'Prednisona e ciclosporina por peso na SSJ/NET e DRESS; anti-histamínicos, zóster, erisipela e celulite.', sobDemanda(() => import('@/pages/plantonista/manual/DermatosesGravesAdulto'), 'DermatosesGravesAdulto'), ['dermatose', 'farmacodermia', 'SSJ', 'NET', 'DRESS', 'urticária', 'angioedema', 'herpes-zóster']),
      t('acessos-calibres-adulto', 'Acessos: calibres, French e intraósseo (adulto)', 'French ↔ mm, tabelas de gauge, agulha IO pelo peso, sítios e lidocaína IO.', sobDemanda(() => import('@/pages/plantonista/manual/AcessosCalibresAdulto'), 'AcessosCalibresAdulto'), ['French', 'gauge', 'calibre', 'jelco', 'abocath', 'cateter', 'intraósseo', 'IO']),
      t('marca-passo-provisorio-adulto', 'Marca-passo provisório — parâmetros (adulto)', 'MPTC (FC, corrente = limiar + 5-10 mA, < 120 min), MPTV às cegas, sensibilidade 50% e saída 2 × limiar + 1, ímã.', sobDemanda(() => import('@/pages/plantonista/manual/MarcaPassoProvisorioAdulto'), 'MarcaPassoProvisorioAdulto'), ['marca-passo', 'transcutâneo', 'transvenoso', 'MPTC', 'MPTV', 'bradicardia', 'limiar', 'captura']),
    ],
  },
  {
    slug: 'escores',
    label: 'Escores',
    description: 'Escalas de gravidade e estratificação de risco.',
    icon: GraduationCap,
    tools: [
      t('glasgow', 'Escala de Coma de Glasgow (GCS-P)', 'Abertura ocular, resposta verbal e resposta motora, com o GCS-P pelas pupilas.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Glasgow'), ['Escala', 'Coma', 'Glasgow', 'GCS-P']),
      t('curb-65', 'CURB-65', 'Gravidade da pneumonia comunitária e mortalidade em 30 dias da coorte original.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Curb65'), ['CURB-65', 'gravidade', 'pneumonia', 'comunitária']),
      t('cha2ds2-va', 'CHA₂DS₂-VA', 'Risco de AVC na fibrilação atrial, sem a categoria de sexo (ESC 2024).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Cha2ds2va'), ['CHA₂DS₂-VA', 'risco', 'fibrilação', 'atrial']),
      t('has-bled', 'HAS-BLED', 'No paciente em anticoagulação oral por fibrilação atrial.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'HasBled'), ['HAS-BLED', 'risco', 'sangramento', 'maior']),
      t('child-pugh', 'Child-Pugh', 'Classe A, B ou C, e a sobrevida estimada.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'ChildPugh'), ['Child-Pugh', 'gravidade', 'cirrose']),
      t('heart', 'HEART', 'Risco de evento cardíaco maior em 6 semanas.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Heart'), ['HEART', 'torácica', 'pronto-socorro']),
      t('wells-tvp', 'Wells para TVP', 'Probabilidade clínica de TVP: nove itens e um subtrator.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'WellsTvp'), ['Wells', 'para', 'probabilidade', 'trombose', 'venosa', 'profunda']),
      t('alvarado', 'Alvarado', 'Oito itens de história, exame e hemograma, de 0 a 10.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Alvarado'), ['Alvarado', 'probabilidade', 'apendicite', 'aguda']),
      t('abcd2', 'ABCD2', 'Risco de AVC em 2 e 7 dias após ataque isquêmico transitório.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Abcd2'), ['ABCD2', 'risco', 'depois']),
      t('4t-hit', '4T', 'Probabilidade pré-teste de trombocitopenia induzida por heparina, de 0 a 8 pontos.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'QuatroT'), ['probabilidade', 'trombocitopenia', 'induzida', 'heparina']),
      t('aims65', 'AIMS65', 'Mortalidade hospitalar na hemorragia digestiva alta com cinco itens da chegada.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Aims65'), ['AIMS65', 'mortalidade', 'hemorragia', 'digestiva', 'alta']),
      t('bisap', 'BISAP', 'Gravidade da pancreatite aguda nas primeiras 24 horas e mortalidade da coorte original.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Bisap'), ['BISAP', 'gravidade', 'pancreatite', 'aguda']),
      t('cam-icu', 'CAM-ICU', 'Delirium no paciente crítico por quatro características, incluindo o intubado.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'CamIcu'), ['CAM-ICU', 'delirium', 'paciente', 'crítico']),
      t('civd-isth', 'CIVD manifesta', 'Quatro parâmetros laboratoriais, 0 a 8 pontos, com a doença de base como pré-requisito.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'CivdIsth'), ['CIVD', 'manifesta', 'escore', 'ISTH']),
      t('canadian-ct-head', 'Canadian CT Head Rule', 'TCE leve no adulto: cinco critérios de alto risco e dois de risco médio.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'CanadianCtHead'), ['Canadian', 'Head', 'Rule', 'leve', 'adulto']),
      t('light', 'Critérios de Light', 'Exsudato ou transudato no derrame pleural, com o gradiente de albumina.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Light'), ['Critérios', 'Light', 'exsudato', 'transudato']),
      t('four', 'FOUR Score', 'Quatro domínios de 0 a 4, sem depender de resposta verbal.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Four'), ['FOUR', 'Score', 'consciência', 'paciente', 'crítico']),
      t('grace', 'GRACE', 'Mortalidade hospitalar na síndrome coronariana aguda por oito variáveis da admissão.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Grace'), ['GRACE', 'risco', 'síndrome', 'coronariana', 'aguda']),
      t('genebra-revisado', 'Genebra revisado', 'Probabilidade pré-teste de embolia pulmonar só com itens objetivos.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'GenebraRevisado'), ['Genebra', 'revisado', 'probabilidade', 'embolia', 'pulmonar']),
      t('glasgow-blatchford', 'Glasgow-Blatchford', 'Risco de necessidade de intervenção na hemorragia digestiva alta, com dados anteriores à endoscopia.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'GlasgowBlatchford'), ['Glasgow-Blatchford', 'hemorragia', 'digestiva', 'alta']),
      t('killip', 'Killip', 'Classe de congestão no infarto, de I a IV, pelo exame físico da admissão.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Killip'), ['Killip', 'classe', 'congestão', 'infarto']),
      t('meld-3', 'MELD 3.0', 'Mortalidade em 3 meses na doença hepática avançada, com MELD-Na e MELD original para comparação.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Meld3'), ['MELD', 'mortalidade', 'doença', 'hepática']),
      t('psi-port', 'PSI / PORT', 'Classe de gravidade da pneumonia adquirida na comunidade e mortalidade em 30 dias da coorte original.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Psi'), ['PORT', 'gravidade', 'pneumonia', 'adquirida', 'comunidade']),
      t('rass', 'RASS', 'Nível de agitação ou sedação, de +4 combativo a −5 sem despertar.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Rass'), ['RASS', 'escala', 'agitação', 'sedação', 'Richmond']),
      t('ranson', 'Ranson', 'Gravidade da pancreatite aguda não biliar: cinco critérios na admissão e seis nas primeiras 48 horas.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Ranson'), ['Ranson', 'gravidade', 'pancreatite', 'biliar']),
      t('rockall', 'Rockall', 'Mortalidade e ressangramento na hemorragia digestiva alta, na forma clínica ou completa.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Rockall'), ['Rockall', 'ressangramento', 'mortalidade']),
      t('sepse-adulto', 'Sepse no adulto', 'Sinal de alerta qSOFA, disfunção orgânica pelo SOFA e clareamento de lactato.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'SepseAdulto'), ['Sepse', 'adulto', 'qSOFA', 'SOFA', 'lactato']),
      t('wells-tep', 'Wells para TEP', 'Probabilidade pré-teste de embolia pulmonar, nas leituras de três níveis e dicotomizada, com o limiar de D-dímero ajustado pela idade.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'WellsTep'), ['Wells', 'para', 'probabilidade', 'embolia', 'pulmonar']),
      t('years', 'YEARS', 'Três itens clínicos e o limiar de D-dímero de 1000 ou 500 ng/mL na suspeita de embolia pulmonar.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'Years'), ['YEARS', 'embolia', 'pulmonar', 'TEP', 'D-dímero']),
      t('pesi', 'Severidade do TEP (PESI)', 'Classes I–V pela Tabela 10 do manual HC.', sobDemanda(() => import('@/pages/plantonista/escores/Pesi'), 'Pesi'), ['TEP', 'embolia', 'pulmonar', 'prognóstico']),
      t('nih-avc', 'NIHSS — AVC', 'Escala do manual HC (15 itens, máximo 42).', sobDemanda(() => import('@/pages/plantonista/manual/EscoresLoteE2'), 'NihssHc'), ['AVC', 'NIHSS', 'déficit', 'neurologia', 'stroke']),
      t('news2', 'NEWS2', 'Alerta precoce de deterioração; rastreio de sepse pela SSC 2026.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresPacote'), 'News2'), ['deterioração', 'escore', 'alerta', 'NEWS 2', 'NEWS2', 'sepse', 'rastreio']),
      t('timi', 'TIMI — Risco', 'Risco em angina instável / IAM sem supra de ST.', sobDemanda(() => import('@/pages/plantonista/escores/Timi'), 'Timi'), ['TIMI', 'angina', 'IAM', 'coronariana', 'risco']),
      t('timi-iamcsst', 'TIMI IAMCSST', 'Mortalidade em 30 dias no IAM com supra de ST por oito variáveis da admissão (Morrow 2000).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'TimiIamcsst'), ['TIMI', 'IAMCSST', 'supra', 'infarto', 'STEMI']),
      t('sincope-san-francisco', 'Síncope — regra de San Francisco', 'Cinco fatores; risco com pelo menos um (manual HC, Tabela 3).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'SincopeSanFrancisco'), ['síncope', 'San Francisco', 'perda de consciência']),
      t('sincope-canadense', 'Síncope — Canadian Syncope Risk Score', 'Nove itens, de −3 a 11, em cinco categorias de risco (Thiruganasambandamoorthy 2016).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'SincopeCanadense'), ['síncope', 'canadense', 'Canadian', 'risco']),
      t('duke-endocardite', 'Critérios de Duke modificados', 'Endocardite infecciosa: 2 maiores, 1 maior e 3 menores ou 5 menores (manual HC, Tabela 2).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'Duke'), ['Duke', 'endocardite', 'ecocardiograma', 'hemocultura']),
      t('iss', 'ISS — Injury Severity Score', 'Soma dos quadrados dos três maiores AIS por região, de 0 a 75 (Baker 1974).', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'Iss'), ['ISS', 'trauma', 'AIS', 'gravidade', 'politrauma']),
      t('ckd-epi', 'TFG estimada — CKD-EPI 2021', 'Creatinina, idade e sexo, sem coeficiente de raça, com a categoria G da KDIGO.', sobDemanda(() => import('@/pages/plantonista/escores/EscoresOnda9'), 'CkdEpi'), ['CKD-EPI', 'TFG', 'filtração glomerular', 'creatinina', 'função renal', 'clearance']),
    ],
  },
  {
    slug: 'protocolos',
    label: 'Protocolos',
    description: 'Condutas padronizadas para situações frequentes.',
    icon: ClipboardList,
    tools: [
      t('hda-lamg', 'Profilaxia de úlcera de estresse', 'Omeprazol e gastroproteção na dupla antiagregação (manual HC).', sobDemanda(() => import('@/pages/plantonista/manual/ProfilaxiaHdaLamg'), 'ProfilaxiaHdaLamg'), ['LAMG', 'úlcera de estresse', 'pantoprazol', 'sangramento digestivo']),
      t('hiperpotassemia', 'Hiperpotassemia', 'Gravidade, cálcio pelo ECG e conduta em três tempos.', sobDemanda(() => import('@/pages/plantonista/protocolos/Hiperpotassemia'), 'Hiperpotassemia'), ['potássio', 'hipercalemia', 'glicoinsulinoterapia', 'gluconato', 'ECG']),
      t('abstinencia', 'Abstinência alcoólica', 'CIWA-Ar, critérios de Caine e doses (manual HC, cap. 78).', sobDemanda(() => import('@/pages/plantonista/manual/Abstinencia'), 'Abstinencia'), ['abstinência', 'álcool', 'CIWA-Ar', 'delirium tremens', 'benzodiazepínico', 'tiamina']),
      t('decanulacao', 'Decanulação', 'Roteiro para retirada da traqueostomia.', sobDemanda(() => import('@/pages/plantonista/protocolos/Decanulacao'), 'Decanulacao'), ['traqueostomia', 'decanulação', 'desmame', 'cânula']),
    ],
  },
  {
    slug: 'farmacia',
    label: 'Farmácia',
    description: 'Consulta de medicamentos, diluições e compatibilidades.',
    icon: FlaskConical,
    tools: [
      t('consulta-medicamentos', 'Consulta de Medicamentos', 'Busca por nome com apresentação, dose e diluição.', sobDemanda(() => import('@/pages/plantonista/farmacia/ConsultaMedicamentos'), 'ConsultaMedicamentos'), ['medicamento', 'prescrição', 'droga', 'diluição', 'apresentação', 'CMED', 'farmácia']),
      t('referencia-diluicao', 'Referência de Diluição', 'Diluições publicadas e revisadas por farmacêutico.', sobDemanda(() => import('@/pages/plantonista/farmacia/ReferenciaDiluicaoTool'), 'ReferenciaDiluicaoTool'), ['diluição', 'reconstituição', 'estabilidade', 'infusão', 'farmácia', 'compatibilidade']),
    ],
  },
  {
    slug: 'dengue',
    label: 'Dengue',
    description: 'Classificação, conduta e hidratação da dengue.',
    icon: Wind,
    tools: [
      t('classificacao-conduta-hidratacao', 'Classificação, Conduta e Hidratação', 'Grupos A–D e hidratação conforme o MS.', sobDemanda(() => import('@/pages/plantonista/dengue/ClassificacaoDengue'), 'ClassificacaoDengue'), ['dengue', 'arbovirose', 'hidratação', 'sinais de alarme', 'choque']),
      t('manual-dengue', 'Dengue — criança', 'Grupos e hidratação por peso (PS Pediatria ICr).', sobDemanda(() => import('@/pages/plantonista/pediatria/DenguePed'), 'DenguePed'), ['dengue', 'manual', 'ministério da saúde']),
    ],
  },
  // Games (Infection, Minigame de Emergência) fora do menu e da busca até o RT
  // aprovar o conteúdo, que ensina dose (decisão do RT, 03/10/2026; auditoria R3).
  // O código continua em pages/plantonista/games para a revisão.
  {
    slug: 'ventilacao-mecanica',
    label: 'Ventilação Mecânica',
    description: 'Suporte ventilatório, VNI e recrutamento pulmonar.',
    icon: Wind,
    tools: [
      t('vm-cinco-passos', 'Ventilação mecânica em cinco passos', 'Quem, modo, ajustes, acompanhamento e desmame com as tabelas do cap. 37 do manual HC.', sobDemanda(() => import('@/pages/plantonista/ventilacao/VmCincoPassos'), 'VmCincoPassos'), ['ventilação mecânica', 'VM', 'PEEP', 'volume corrente', 'platô', 'driving pressure', 'desmame', 'alarmes']),
      t('vni-cinco-passos', 'VNI em cinco passos', 'Indicação, interface, ajustes, acompanhamento e retirada com o que o manual HC traz.', sobDemanda(() => import('@/pages/plantonista/ventilacao/VniCincoPassos'), 'VniCincoPassos'), ['VNI', 'ventilação não invasiva', 'BiPAP', 'CPAP', 'IPAP', 'EPAP']),
      t('manobra-recrutamento', 'SDRA — ventilação protetora', 'Berlim, PEEP × FiO₂ e prona (manual HC, cap. 37).', sobDemanda(() => import('@/pages/plantonista/manual/SdraVentilacaoAdulto'), 'SdraVentilacaoAdulto'), ['recrutamento', 'PEEP', 'SARA', 'manobra']),
      t('suporte-ventilatorio', 'Ventilação mecânica — ajuste inicial', 'Parâmetros iniciais por modo e relação I:E (manual HC, cap. 37).', sobDemanda(() => import('@/pages/plantonista/manual/VmAjusteInicialAdulto'), 'VmAjusteInicialAdulto'), ['ventilação mecânica', 'VM', 'volume corrente', 'P/F', 'proteção pulmonar']),
      t('mobilidade-funcional', 'Mobilidade Funcional', 'Níveis e critérios de mobilização.', sobDemanda(() => import('@/pages/plantonista/ventilacao/MobilidadeFuncional'), 'MobilidadeFuncional'), ['mobilização', 'fisioterapia', 'ambulação', 'UTI']),
    ],
  },
]

/** Todas as chaves `secao/slug` — usado para migrar favoritos/recentes antigos. */
export const CHAVES_FERRAMENTAS: string[] = SECOES.flatMap((s) =>
  s.tools.map((tool) => chaveFerramenta(s.slug, tool.slug))
)

export function acharSecao(slug: string) {
  return SECOES.find((s) => s.slug === slug)
}
