// Onde cada ficha do pacote aparece no app (para a Revisão Clínica abrir a tela).
export const ROTA_DA_FICHA: Record<string, string> = {
  'acesso-venoso': '/plantonista/calculadoras/acesso-venoso',
  'dengue-classificacao': '/plantonista/dengue/classificacao-conduta-hidratacao',
  'hiperpotassemia': '/plantonista/protocolos/hiperpotassemia',
  'glasgow': '/plantonista/escores/glasgow',
  'curb-65': '/plantonista/escores/curb-65',
  'cha2ds2-va': '/plantonista/escores/cha2ds2-va',
  'has-bled': '/plantonista/escores/has-bled',
  'child-pugh': '/plantonista/escores/child-pugh',
  'heart': '/plantonista/escores/heart',
  'wells-tvp': '/plantonista/escores/wells-tvp',
  'alvarado': '/plantonista/escores/alvarado',
  'abcd2': '/plantonista/escores/abcd2',
  '4t-hit': '/plantonista/escores/4t-hit',
  'aims65': '/plantonista/escores/aims65',
  'bisap': '/plantonista/escores/bisap',
  'cam-icu': '/plantonista/escores/cam-icu',
  'civd-isth': '/plantonista/escores/civd-isth',
  'canadian-ct-head': '/plantonista/escores/canadian-ct-head',
  'light': '/plantonista/escores/light',
  'four': '/plantonista/escores/four',
  'grace': '/plantonista/escores/grace',
  'genebra-revisado': '/plantonista/escores/genebra-revisado',
  'glasgow-blatchford': '/plantonista/escores/glasgow-blatchford',
  'killip': '/plantonista/escores/killip',
  'meld-3': '/plantonista/escores/meld-3',
  'psi-port': '/plantonista/escores/psi-port',
  'rass': '/plantonista/escores/rass',
  'ranson': '/plantonista/escores/ranson',
  'rockall': '/plantonista/escores/rockall',
  'sepse-adulto': '/plantonista/escores/sepse-adulto',
  'wells-tep': '/plantonista/escores/wells-tep',
  'news2': '/plantonista/escores/news2',
  'ped-bolus': '/plantonista/pediatria/bolus',
  'ped-via-aerea': '/plantonista/pediatria/via-aerea',
}
