-- Onda 9 do porte (ferramentas clínicas da Central): registra as versões das
-- fichas novas de src/clinico no mesmo formato de scripts/fichas-sql.mjs. Cada
-- versão entra AGUARDANDO APROVAÇÃO do responsável técnico (Revisão Clínica);
-- a tela mostra a faixa "aguardando aprovação" até a decisão. Versão já
-- registrada não muda (a função ignora a repetição).
SELECT private.registrar_versao_ferramenta('adulto-duke-modificado', 'Critérios de Duke modificados — endocardite infecciosa (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Brandão Neto RA, et al. (eds.). Manual de Medicina de Emergência — Disciplina de Emergências Clínicas, Hospital das Clínicas da FMUSP. 3ª ed. rev. e atual. Santana de Parnaíba: Manole; 2022. ISBN 9786555767827. cap. 23 Endocardite infecciosa, p. 324–326 (Tabela 2)."}]'::jsonb);
SELECT private.registrar_versao_ferramenta('adulto-sincope-san-francisco', 'Regra de San Francisco — síncope (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Brandão Neto RA, et al. (eds.). Manual de Medicina de Emergência — Disciplina de Emergências Clínicas, Hospital das Clínicas da FMUSP. 3ª ed. rev. e atual. Santana de Parnaíba: Manole; 2022. ISBN 9786555767827. cap. 16 Perda transitória da consciência, p. 237–238 (Tabela 3)."}]'::jsonb);
SELECT private.registrar_versao_ferramenta('adulto-vm-cinco-passos', 'Ventilação mecânica em cinco passos (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Brandão Neto RA, et al. (eds.). Manual de Medicina de Emergência — Disciplina de Emergências Clínicas, Hospital das Clínicas da FMUSP. 3ª ed. rev. e atual. Santana de Parnaíba: Manole; 2022. ISBN 9786555767827. cap. 37, p. 498–510 (Tabelas 2, 4, 5, 6 e 7; Figuras 4 e 5)."}]'::jsonb);
SELECT private.registrar_versao_ferramenta('adulto-vni-cinco-passos', 'Ventilação não invasiva em cinco passos (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Brandão Neto RA, et al. (eds.). Manual de Medicina de Emergência — Disciplina de Emergências Clínicas, Hospital das Clínicas da FMUSP. 3ª ed. rev. e atual. Santana de Parnaíba: Manole; 2022. ISBN 9786555767827. cap. 27, p. 378–386; cap. 31, p. 424–426; cap. 21, p. 296; cap. 1, p. 35–36."}]'::jsonb);
SELECT private.registrar_versao_ferramenta('ckd-epi-2021', 'TFG estimada — CKD-EPI 2021 (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Inker LA, Eneanya ND, Coresh J, et al. New Creatinine- and Cystatin C–Based Equations to Estimate GFR without Race. N Engl J Med. 2021;385(19):1737–1749.","url":"https://doi.org/10.1056/NEJMoa2102953"},{"citacao":"Kidney Disease: Improving Global Outcomes (KDIGO) CKD Work Group. KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease. Kidney Int. 2024;105(4S):S117–S314. Categorias de TFG G1–G5.","url":"https://doi.org/10.1016/j.kint.2023.10.018"}]'::jsonb);
SELECT private.registrar_versao_ferramenta('iss', 'ISS — Injury Severity Score (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Baker SP, O''Neill B, Haddon W Jr, Long WB. The Injury Severity Score: a method for describing patients with multiple injuries and evaluating emergency care. J Trauma. 1974;14(3):187–196.","url":"https://doi.org/10.1097/00005373-197403000-00001"}]'::jsonb);
SELECT private.registrar_versao_ferramenta('ped-phoenix', 'Escore de Phoenix — sepse e choque séptico (criança)', '2026-09-30.1', 'pediatrico', '[{"citacao":"Schlapbach LJ, Watson RS, Sorce LR, et al. International Consensus Criteria for Pediatric Sepsis and Septic Shock (Phoenix). JAMA. 2024;331(8):665–674. Tabela do escore (p. E3 do PDF).","url":"https://doi.org/10.1001/jama.2024.0179","pediatrica":true}]'::jsonb);
SELECT private.registrar_versao_ferramenta('ped-pram', 'PRAM — gravidade da crise de asma (criança)', '2026-09-30.1', 'pediatrico', '[{"citacao":"Ducharme FM, Chalut D, Plotnick L, et al. The Pediatric Respiratory Assessment Measure: a valid clinical score for assessing acute asthma severity from toddlers to teenagers. J Pediatr. 2008;152(4):476–480.","url":"https://doi.org/10.1016/j.jpeds.2007.08.034","pediatrica":true},{"citacao":"Chalut DS, Ducharme FM, Davis GM. The Preschool Respiratory Assessment Measure (PRAM): a responsive index of acute asthma severity. J Pediatr. 2000;137(6):762–768.","url":"https://doi.org/10.1067/mpd.2000.110121","pediatrica":true}]'::jsonb);
SELECT private.registrar_versao_ferramenta('ped-tfg-schwartz', 'TFG estimada — Schwartz / CKiD (criança)', '2026-09-30.1', 'pediatrico', '[{"citacao":"Schvartsman C, et al. (coords.). Pronto-Socorro — Pediatria ICr-HCFMUSP. 4ª ed. Santana de Parnaíba: Manole; 2023. ISBN 978-65-5576-759-9. cap. 56, p. 575–576 (Tabela 2).","pediatrica":true}]'::jsonb);
SELECT private.registrar_versao_ferramenta('sincope-canadense', 'Canadian Syncope Risk Score — síncope no pronto-socorro (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Thiruganasambandamoorthy V, Kwong K, Wells GA, et al. Development of the Canadian Syncope Risk Score to predict serious adverse events after emergency department assessment of syncope. CMAJ. 2016;188(12):E289–E298.","url":"https://doi.org/10.1503/cmaj.151469"}]'::jsonb);
SELECT private.registrar_versao_ferramenta('timi-iamcsst', 'TIMI IAMCSST — risco no IAM com supra de ST (adulto)', '2026-09-30.1', 'adulto', '[{"citacao":"Morrow DA, Antman EM, Charlesworth A, et al. TIMI risk score for ST-elevation myocardial infarction: a convenient, bedside, clinical score for risk assessment at presentation. An intravenous nPA for treatment of infarcting myocardium early II trial substudy. Circulation. 2000;102(17):2031–2037.","url":"https://doi.org/10.1161/01.CIR.102.17.2031"}]'::jsonb);
