-- ─────────────────────────────────────────────────────────────────────────────
-- Fase 3 — Base de medicamentos para o teste de prescrição
-- Adiciona coluna de diluição e popula a base com medicamentos comuns.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.medicamentos
  ADD COLUMN IF NOT EXISTS diluicao text;

INSERT INTO public.medicamentos (nome, principio_ativo, concentracao, forma_farmaceutica, apresentacao, via, unidade, diluicao) VALUES
  ('Soro Fisiológico 0,9%', 'Cloreto de sódio', '0,9%', 'Solução injetável', '500 mL', 'EV', 'ml', NULL),
  ('Soro Glicosado 5%', 'Glicose', '5%', 'Solução injetável', '500 mL', 'EV', 'ml', NULL),
  ('Soro Glicosado 10%', 'Glicose', '10%', 'Solução injetável', '500 mL', 'EV', 'ml', NULL),
  ('Ringer Lactato', 'Sódio, potássio, cálcio e lactato', 'Eletrolítico', 'Solução injetável', '500 mL', 'EV', 'ml', NULL),
  ('Dipirona', 'Dipirona sódica', '500 mg/mL', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 100 mL de soro fisiológico 0,9% para infusão EV'),
  ('Dipirona Comprimido', 'Dipirona sódica', '500 mg', 'Comprimido', 'Blister com 10', 'VO', 'mg', NULL),
  ('Paracetamol', 'Paracetamol', '500 mg', 'Comprimido', 'Blister com 20', 'VO', 'mg', NULL),
  ('Paracetamol Gotas', 'Paracetamol', '200 mg/mL', 'Solução oral', 'Frasco 15 mL', 'VO', 'mg', NULL),
  ('Ibuprofeno', 'Ibuprofeno', '600 mg', 'Comprimido revestido', 'Blister com 20', 'VO', 'mg', NULL),
  ('Omeprazol', 'Omeprazol', '40 mg', 'Pó liofilizado injetável', 'Frasco-ampola', 'EV', 'mg', 'Reconstituir com 10 mL de água para injeção e diluir em 100 mL de soro fisiológico 0,9%'),
  ('Ondansetrona', 'Ondansetrona', '8 mg', 'Solução injetável', 'Ampola 4 mL', 'EV', 'mg', 'Diluir em 50 mL de soro fisiológico 0,9% ou glicosado 5% e infundir em 15 min'),
  ('Metoclopramida', 'Metoclopramida', '10 mg', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 50 mL de soro fisiológico 0,9% para infusão lenta (EV)'),
  ('Bromoprida', 'Bromoprida', '5 mg/mL', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 50 mL de soro fisiológico 0,9% para infusão EV'),
  ('Hioscina', 'Escopolamina butilbrometo', '20 mg/mL', 'Solução injetável', 'Ampola 1 mL', 'EV/IM', 'mg', 'Diluir em 100 mL de soro fisiológico 0,9% para infusão EV'),
  ('Morfina', 'Sulfato de morfina', '10 mg/mL', 'Solução injetável', 'Ampola 1 mL', 'EV/IM/SC', 'mg', 'Diluir em 10 mL de soro fisiológico 0,9% para administração EV lenta (diluição de rotina em bomba)'),
  ('Tramadol', 'Cloridrato de tramadol', '50 mg/mL', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 100 mL de soro fisiológico 0,9% ou glicosado 5% para infusão EV'),
  ('Cetoprofeno', 'Cetoprofeno', '100 mg', 'Solução injetável', 'Frasco-ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 100 mL de soro fisiológico 0,9% para infusão EV (mín. 30 min)'),
  ('Tenoxicam', 'Tenoxicam', '20 mg', 'Pó liofilizado injetável', 'Frasco-ampola', 'EV/IM', 'mg', 'Reconstituir e diluir em 50 mL de soro fisiológico 0,9% para infusão EV'),
  ('Ácido acetilsalicílico', 'AAS', '100 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Clopidogrel', 'Clopidogrel', '75 mg', 'Comprimido revestido', 'Blister com 28', 'VO', 'mg', NULL),
  ('Enoxaparina', 'Enoxaparina sódica', '60 mg/0,6 mL', 'Solução injetável', 'Seringa preenchida 0,6 mL', 'SC', 'mg', NULL),
  ('Heparina', 'Heparina sódica', '5000 UI/mL', 'Solução injetável', 'Frasco-ampola 5 mL', 'EV/SC', 'UI', NULL),
  ('Ceftriaxona', 'Ceftriaxona sódica', '1 g', 'Pó para solução injetável', 'Frasco-ampola', 'EV/IM', 'mg', 'Reconstituir com 10 mL de água para injeção; diluir em 100 mL de soro fisiológico 0,9% para infusão EV'),
  ('Amoxicilina + Clavulanato', 'Amoxicilina + clavulanato', '875 mg + 125 mg', 'Comprimido revestido', 'Blister com 14', 'VO', 'mg', NULL),
  ('Azitromicina', 'Azitromicina', '500 mg', 'Comprimido', 'Blister com 5', 'VO', 'mg', NULL),
  ('Ciprofloxacino', 'Ciprofloxacino', '500 mg', 'Comprimido', 'Blister com 14', 'VO', 'mg', NULL),
  ('Levofloxacino', 'Levofloxacino', '500 mg', 'Solução injetável', 'Frasco 100 mL', 'EV', 'mg', 'Administrar em 60 min (pré-diluído)'),
  ('Metronidazol', 'Metronidazol', '500 mg/100 mL', 'Solução injetável', 'Frasco 100 mL', 'EV', 'mg', 'Administrar em 60 min (pré-diluído)'),
  ('Clindamicina', 'Clindamicina', '600 mg', 'Solução injetável', 'Ampola 4 mL', 'EV', 'mg', 'Diluir em 100 mL de soro fisiológico 0,9% ou glicosado 5% e infundir em 30 min'),
  ('Vancomicina', 'Vancomicina', '500 mg', 'Pó para solução injetável', 'Frasco-ampola', 'EV', 'mg', 'Reconstituir e diluir em 100–250 mL de soro fisiológico 0,9%; infundir em 60 min'),
  ('Furosemida', 'Furosemida', '10 mg/mL', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 50 mL de soro fisiológico 0,9% para infusão EV lenta'),
  ('Hidroclorotiazida', 'Hidroclorotiazida', '25 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Enalapril', 'Maleato de enalapril', '10 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Losartana', 'Losartana potássica', '50 mg', 'Comprimido revestido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Atenolol', 'Atenolol', '50 mg', 'Comprimido', 'Blister com 28', 'VO', 'mg', NULL),
  ('Metoprolol', 'Succinato de metoprolol', '25 mg', 'Comprimido de liberação prolongada', 'Blister com 30', 'VO', 'mg', NULL),
  ('Amiodarona', 'Amiodarona', '150 mg/3 mL', 'Solução injetável', 'Ampola 3 mL', 'EV', 'mg', 'Diluir em 250 mL de soro glicosado 5% para infusão EV'),
  ('Dexametasona', 'Dexametasona', '4 mg/mL', 'Solução injetável', 'Ampola 1 mL', 'EV/IM', 'mg', NULL),
  ('Hidrocortisona', 'Hidrocortisona', '100 mg', 'Pó para solução injetável', 'Frasco-ampola', 'EV/IM', 'mg', 'Reconstituir com 2 mL de água para injeção'),
  ('Metilprednisolona', 'Metilprednisolona', '125 mg', 'Pó para solução injetável', 'Frasco-ampola', 'EV', 'mg', 'Reconstituir e diluir em 100 mL de soro fisiológico 0,9% para infusão EV'),
  ('Prednisona', 'Prednisona', '20 mg', 'Comprimido', 'Blister com 10', 'VO', 'mg', NULL),
  ('Salbutamol', 'Sulfato de salbutamol', '100 mcg/dose', 'Spray aerosol', 'Frasco 200 doses', 'INAL', 'dose', NULL),
  ('Brometo de ipratrópio', 'Ipratrópio', '20 mcg/dose', 'Spray aerosol', 'Frasco 200 doses', 'INAL', 'dose', NULL),
  ('Fenoterol', 'Fenoterol', '0,5 mg/mL', 'Solução para nebulização', 'Frasco 20 mL', 'INAL', 'mg', 'Diluir em 3 mL de soro fisiológico 0,9% para nebulização'),
  ('Insulina Regular', 'Insulina humana regular', '100 UI/mL', 'Solução injetável', 'Frasco 10 mL', 'SC/EV', 'UI', NULL),
  ('Insulina NPH', 'Insulina NPH', '100 UI/mL', 'Suspensão injetável', 'Frasco 10 mL', 'SC', 'UI', NULL),
  ('Glicose 50%', 'Glicose', '50%', 'Solução injetável', 'Ampola 10 mL', 'EV', 'ml', 'Administrar EV lenta (dose por hipoglicemia)'),
  ('Glicose 25%', 'Glicose', '25%', 'Solução injetável', 'Frasco-ampola 20 mL', 'EV', 'ml', NULL),
  ('Sulfato de magnésio', 'Sulfato de magnésio', '500 mg/mL', 'Solução injetável', 'Ampola 10 mL', 'EV/IM', 'mg', 'Diluir em 100 mL de soro fisiológico 0,9% e infundir em 20–60 min'),
  ('Gluconato de cálcio', 'Gluconato de cálcio', '100 mg/mL', 'Solução injetável', 'Ampola 10 mL', 'EV', 'mg', 'Diluir em 100 mL de soro glicosado 5% para infusão EV lenta'),
  ('Prometazina', 'Prometazina', '25 mg/mL', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 50 mL de soro fisiológico 0,9% para infusão EV'),
  ('Dimenidrinato', 'Dimenidrinato', '50 mg/mL', 'Solução injetável', 'Ampola 1 mL', 'EV/IM', 'mg', 'Diluir em 50 mL de soro fisiológico 0,9% para infusão EV'),
  ('Ranitidina', 'Cloridrato de ranitidina', '50 mg', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', 'Diluir em 100 mL de soro glicosado 5% para infusão EV'),
  ('Escitalopram', 'Escitalopram', '20 mg', 'Comprimido revestido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Sertralina', 'Sertralina', '50 mg', 'Comprimido revestido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Diazepam', 'Diazepam', '10 mg/2 mL', 'Solução injetável', 'Ampola 2 mL', 'EV/IM', 'mg', NULL),
  ('Midazolam', 'Midazolam', '15 mg/3 mL', 'Solução injetável', 'Ampola 3 mL', 'EV/IM', 'mg', 'Diluir com soro fisiológico 0,9% conforme protocolo de sedação'),
  ('Lorazepam', 'Lorazepam', '2 mg', 'Comprimido', 'Blister com 30', 'VO/SL', 'mg', NULL),
  ('Fenitoína', 'Fenitoína', '50 mg/mL', 'Solução injetável', 'Ampola 5 mL', 'EV', 'mg', 'Diluir em 100–250 mL de soro fisiológico 0,9%; não usar soro glicosado'),
  ('Fenobarbital', 'Fenobarbital', '100 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Levotiroxina', 'Levotiroxina sódica', '100 mcg', 'Comprimido', 'Blister com 30', 'VO', 'mcg', NULL),
  ('Clonazepam', 'Clonazepam', '2 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Espironolactona', 'Espironolactona', '25 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Digoxina', 'Digoxina', '0,25 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Carvedilol', 'Carvedilol', '6,25 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Anlodipino', 'Besilato de anlodipino', '5 mg', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Ácido fólico', 'Ácido fólico', '5 mg', 'Comprimido', 'Blister com 20', 'VO', 'mg', NULL),
  ('Sulfato ferroso', 'Sulfato ferroso', '40 mg Fe', 'Comprimido', 'Blister com 30', 'VO', 'mg', NULL),
  ('Vitamina B12', 'Cianocobalamina', '1000 mcg/mL', 'Solução injetável', 'Ampola 1 mL', 'IM', 'mcg', NULL),
  ('Ocitocina', 'Ocitocina', '5 UI/mL', 'Solução injetável', 'Ampola 1 mL', 'EV/IM', 'UI', 'Diluir em soro fisiológico 0,9% conforme protocolo (infusão em bomba)'),
  ('Misoprostol', 'Misoprostol', '25 mcg', 'Comprimido', 'Blister com 4', 'SL/VG', 'mcg', NULL)
ON CONFLICT DO NOTHING;
