-- Pilar 1 (tuning de performance): índices nas FKs usadas em RLS/join das
-- tabelas clínicas secundárias (unidade_id/paciente_id/episodio_id/
-- internacao_id/setor_id/medicamento_id/organizacao_id/plantao_id/pacote_id/
-- documento_id/prescricao_item_id/pendencia_id/sala_id). Toda policy filtra por
-- essas colunas (papel_na_unidade/paciente_no_meu_plantao) → sem índice = seq
-- scan por query. Colunas de AUDITORIA (*_por, autor_id) ficam SEM índice de
-- propósito (raramente filtradas; evita over-index). Gerado de auditoria de FK
-- sem índice em 01/10/2026. Reaplicável (IF NOT EXISTS).

CREATE INDEX IF NOT EXISTS idx_acuidade_afericoes_unidade_id ON public.acuidade_afericoes (unidade_id);
CREATE INDEX IF NOT EXISTS idx_administracoes_paciente_id ON public.administracoes (paciente_id);
CREATE INDEX IF NOT EXISTS idx_administracoes_unidade_id ON public.administracoes (unidade_id);
CREATE INDEX IF NOT EXISTS idx_admissao_detalhes_obrigatorio_unidade_id ON public.admissao_detalhes_obrigatorio (unidade_id);
CREATE INDEX IF NOT EXISTS idx_admissao_fichas_paciente_id ON public.admissao_fichas (paciente_id);
CREATE INDEX IF NOT EXISTS idx_admissao_fichas_setor_id ON public.admissao_fichas (setor_id);
CREATE INDEX IF NOT EXISTS idx_agravos_notificacao_episodio_id ON public.agravos_notificacao (episodio_id);
CREATE INDEX IF NOT EXISTS idx_agravos_notificacao_internacao_id ON public.agravos_notificacao (internacao_id);
CREATE INDEX IF NOT EXISTS idx_agravos_notificacao_paciente_id ON public.agravos_notificacao (paciente_id);
CREATE INDEX IF NOT EXISTS idx_alergias_negacoes_unidade_id ON public.alergias_negacoes (unidade_id);
CREATE INDEX IF NOT EXISTS idx_alergias_paciente_medicamento_id ON public.alergias_paciente (medicamento_id);
CREATE INDEX IF NOT EXISTS idx_alergias_paciente_unidade_id ON public.alergias_paciente (unidade_id);
CREATE INDEX IF NOT EXISTS idx_atendimento_rascunhos_unidade_id ON public.atendimento_rascunhos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_atendimento_reavaliacoes_paciente_id ON public.atendimento_reavaliacoes (paciente_id);
CREATE INDEX IF NOT EXISTS idx_atendimento_reavaliacoes_unidade_id ON public.atendimento_reavaliacoes (unidade_id);
CREATE INDEX IF NOT EXISTS idx_atendimento_registros_paciente_id ON public.atendimento_registros (paciente_id);
CREATE INDEX IF NOT EXISTS idx_atendimento_registros_unidade_id ON public.atendimento_registros (unidade_id);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_escala_episodio_id ON public.avaliacoes_escala (episodio_id);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_escala_internacao_id ON public.avaliacoes_escala (internacao_id);
CREATE INDEX IF NOT EXISTS idx_avaliacoes_escala_unidade_id ON public.avaliacoes_escala (unidade_id);
CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_episodio_id ON public.balanco_hidrico (episodio_id);
CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_internacao_id ON public.balanco_hidrico (internacao_id);
CREATE INDEX IF NOT EXISTS idx_balanco_hidrico_unidade_id ON public.balanco_hidrico (unidade_id);
CREATE INDEX IF NOT EXISTS idx_chamadas_sala_id ON public.chamadas (sala_id);
CREATE INDEX IF NOT EXISTS idx_chamadas_unidade_id ON public.chamadas (unidade_id);
CREATE INDEX IF NOT EXISTS idx_classificacoes_risco_paciente_id ON public.classificacoes_risco (paciente_id);
CREATE INDEX IF NOT EXISTS idx_classificacoes_risco_unidade_id ON public.classificacoes_risco (unidade_id);
CREATE INDEX IF NOT EXISTS idx_curativos_enfermagem_episodio_id ON public.curativos_enfermagem (episodio_id);
CREATE INDEX IF NOT EXISTS idx_curativos_enfermagem_internacao_id ON public.curativos_enfermagem (internacao_id);
CREATE INDEX IF NOT EXISTS idx_curativos_enfermagem_unidade_id ON public.curativos_enfermagem (unidade_id);
CREATE INDEX IF NOT EXISTS idx_destinacoes_prontuario_unidade_id ON public.destinacoes_prontuario (unidade_id);
CREATE INDEX IF NOT EXISTS idx_diagnosticos_episodio_episodio_id ON public.diagnosticos_episodio (episodio_id);
CREATE INDEX IF NOT EXISTS idx_diagnosticos_episodio_unidade_id ON public.diagnosticos_episodio (unidade_id);
CREATE INDEX IF NOT EXISTS idx_dispositivos_enfermagem_episodio_id ON public.dispositivos_enfermagem (episodio_id);
CREATE INDEX IF NOT EXISTS idx_dispositivos_enfermagem_internacao_id ON public.dispositivos_enfermagem (internacao_id);
CREATE INDEX IF NOT EXISTS idx_dispositivos_enfermagem_unidade_id ON public.dispositivos_enfermagem (unidade_id);
CREATE INDEX IF NOT EXISTS idx_encaminhamentos_internos_episodio_id ON public.encaminhamentos_internos (episodio_id);
CREATE INDEX IF NOT EXISTS idx_encaminhamentos_internos_internacao_id ON public.encaminhamentos_internos (internacao_id);
CREATE INDEX IF NOT EXISTS idx_episodios_unidade_id ON public.episodios (unidade_id);
CREATE INDEX IF NOT EXISTS idx_erros_cliente_unidade_id ON public.erros_cliente (unidade_id);
CREATE INDEX IF NOT EXISTS idx_estoque_medicamento_medicamento_id ON public.estoque_medicamento (medicamento_id);
CREATE INDEX IF NOT EXISTS idx_eventos_adversos_graus_paciente_id ON public.eventos_adversos_graus (paciente_id);
CREATE INDEX IF NOT EXISTS idx_eventos_adversos_graus_unidade_id ON public.eventos_adversos_graus (unidade_id);
CREATE INDEX IF NOT EXISTS idx_eventos_adversos_prescricao_item_id ON public.eventos_adversos (prescricao_item_id);
CREATE INDEX IF NOT EXISTS idx_eventos_adversos_unidade_id ON public.eventos_adversos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_exames_pedidos_documento_id ON public.exames_pedidos (documento_id);
CREATE INDEX IF NOT EXISTS idx_exames_pedidos_episodio_id ON public.exames_pedidos (episodio_id);
CREATE INDEX IF NOT EXISTS idx_exames_pedidos_internacao_id ON public.exames_pedidos (internacao_id);
CREATE INDEX IF NOT EXISTS idx_exames_pedidos_unidade_id ON public.exames_pedidos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_faltas_medicamento_medicamento_id ON public.faltas_medicamento (medicamento_id);
CREATE INDEX IF NOT EXISTS idx_observacao_eventos_paciente_id ON public.observacao_eventos (paciente_id);
CREATE INDEX IF NOT EXISTS idx_observacao_eventos_pendencia_id ON public.observacao_eventos (pendencia_id);
CREATE INDEX IF NOT EXISTS idx_observacao_eventos_unidade_id ON public.observacao_eventos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_observacao_protocolo_etapas_paciente_id ON public.observacao_protocolo_etapas (paciente_id);
CREATE INDEX IF NOT EXISTS idx_observacao_protocolo_etapas_unidade_id ON public.observacao_protocolo_etapas (unidade_id);
CREATE INDEX IF NOT EXISTS idx_observacao_protocolos_paciente_id ON public.observacao_protocolos (paciente_id);
CREATE INDEX IF NOT EXISTS idx_observacao_protocolos_unidade_id ON public.observacao_protocolos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_pacotes_alta_acessos_pacote_id ON public.pacotes_alta_acessos (pacote_id);
CREATE INDEX IF NOT EXISTS idx_pacotes_alta_paciente_id ON public.pacotes_alta (paciente_id);
CREATE INDEX IF NOT EXISTS idx_pacotes_alta_unidade_id ON public.pacotes_alta (unidade_id);
CREATE INDEX IF NOT EXISTS idx_panorama_preferencias_unidade_id ON public.panorama_preferencias (unidade_id);
CREATE INDEX IF NOT EXISTS idx_pareceres_medicos_episodio_id ON public.pareceres_medicos (episodio_id);
CREATE INDEX IF NOT EXISTS idx_pareceres_medicos_organizacao_id ON public.pareceres_medicos (organizacao_id);
CREATE INDEX IF NOT EXISTS idx_passagens_enfermagem_plantao_id ON public.passagens_enfermagem (plantao_id);
CREATE INDEX IF NOT EXISTS idx_passagens_enfermagem_unidade_id ON public.passagens_enfermagem (unidade_id);
CREATE INDEX IF NOT EXISTS idx_passagens_plantao_paciente_id ON public.passagens_plantao (paciente_id);
CREATE INDEX IF NOT EXISTS idx_passagens_plantao_setor_id ON public.passagens_plantao (setor_id);
CREATE INDEX IF NOT EXISTS idx_passagens_plantao_unidade_id ON public.passagens_plantao (unidade_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_acesso_prontuario_organizacao_id ON public.pedidos_acesso_prontuario (organizacao_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_acesso_prontuario_paciente_id ON public.pedidos_acesso_prontuario (paciente_id);
CREATE INDEX IF NOT EXISTS idx_pendencias_paciente_id ON public.pendencias (paciente_id);
CREATE INDEX IF NOT EXISTS idx_pendencias_unidade_id ON public.pendencias (unidade_id);
CREATE INDEX IF NOT EXISTS idx_preferencias_prescricao_medicamento_id ON public.preferencias_prescricao (medicamento_id);
CREATE INDEX IF NOT EXISTS idx_prescricoes_episodio_id ON public.prescricoes (episodio_id);
CREATE INDEX IF NOT EXISTS idx_receita_protocolos_versoes_unidade_id ON public.receita_protocolos_versoes (unidade_id);
CREATE INDEX IF NOT EXISTS idx_sae_registros_episodio_id ON public.sae_registros (episodio_id);
CREATE INDEX IF NOT EXISTS idx_sae_registros_internacao_id ON public.sae_registros (internacao_id);
CREATE INDEX IF NOT EXISTS idx_sae_registros_unidade_id ON public.sae_registros (unidade_id);
CREATE INDEX IF NOT EXISTS idx_sincronizacao_revisao_paciente_id ON public.sincronizacao_revisao (paciente_id);
CREATE INDEX IF NOT EXISTS idx_teleinterconsultas_episodio_id ON public.teleinterconsultas (episodio_id);
CREATE INDEX IF NOT EXISTS idx_teleinterconsultas_organizacao_id ON public.teleinterconsultas (organizacao_id);
CREATE INDEX IF NOT EXISTS idx_termos_cancelamentos_paciente_id ON public.termos_cancelamentos (paciente_id);
CREATE INDEX IF NOT EXISTS idx_termos_cancelamentos_unidade_id ON public.termos_cancelamentos (unidade_id);
CREATE INDEX IF NOT EXISTS idx_validacoes_prescricao_unidade_id ON public.validacoes_prescricao (unidade_id);
